### ISSUE TITLE
Example for "Direct use of join table" not working by it self

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/EntityFramework.Docs#4552] opened 2023-11-12 19:36 UTC
The example for the direct use of the join table is missing the context configuration resulting in the following error:

```
Unable to create a 'DbContext' of type ''. The exception 'The entity type 'PostTag' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

This error is misleading as `HasNoKey` is not a solution here.

This would be the missing config:
```
builder.Entity<Post>()
    .HasMany<Tag>()
    .WithMany()
    .UsingEntity<PostTag>(
        r => r.HasOne(e => e.Tag).WithMany(e => e.PostTags).HasForeignKey(e => e.TagId),
        l => l.HasOne(e => e.Post).WithMany(e => e.PostTags).HasForeignKey(e => e.PostId)
        );
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9234f104-802f-8ee0-8a54-ff3b8f49857e
* Version Independent ID: 9234f104-802f-8ee0-8a54-ff3b8f49857e
* Content: [Many-to-many relationships - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#direct-use-of-join-table)
* Content Source: [entity-framework/core/modeling/relationships/many-to-many.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships/many-to-many.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-11-15 11:08
@LunicLynx Are you running the code from the sample, or have you attempted to recreate the code in your own application? If the latter, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-01-18 18:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-18 18:23 UTC
