### ISSUE TITLE
Sample Application DataGrid sample data not loading

### ISSUE THREAD

**Issue by kuznickic** [dotnet/EntityFramework.Docs#3172] opened 2021-03-22 10:50 UTC
This issue tracker is for ***documentation***
When building the sample application and running it, no data loads into the DataGrids.  Also had to change the Data Source to the full file path to even seed the database.  
For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by ajcvickers** [comment] 2021-03-23 16:14
@kuznickic Can you post a link to the sample to which you are referring?

**Comment by ajcvickers** [comment] 2021-04-01 16:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-04-01 16:16 UTC
