### ISSUE TITLE
Why don't you show the using statements?

### ISSUE THREAD

**Issue by boatcoder** [dotnet/EntityFramework.Docs#3261] opened 2021-05-25 01:22 UTC
You have code displayed without any of the imports/using statements.  This helps me how?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-05-25 22:53
Duplicate of #729

**Closed by ajcvickers** 2021-05-25 22:53 UTC
