### ISSUE TITLE
'Mapping a queryable function to a table-valued function' modelBuilder script example is not updated

### ISSUE THREAD

**Issue by farlop** [dotnet/EntityFramework.Docs#2956] opened 2020-12-22 10:19 UTC
Doc says that binding should be done as:
```
modelBuilder.Entity<Post>().ToTable("Posts");
**modelBuilder.HasDbFunction(typeof(BloggingContext).GetMethod(nameof(PostsWithPopularComments), new[] { typeof(int) }));**
```

But in what's new in EF 5.0 the `HasDbFunctions `is done using an Expression:
`modelBuilder.HasDbFunction(() => GetReports(default));`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34d3f39-600f-0c37-a0a4-11a245d3010c
* Version Independent ID: 5b51ed49-1035-1a8f-a08e-7400d571c77b
* Content: [User-defined function mapping - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping)
* Content Source: [entity-framework/core/querying/user-defined-function-mapping.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/user-defined-function-mapping.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @maumar
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment] 2020-12-22 17:06
Duplicate of #2925

**Closed by smitpatel** 2020-12-22 17:06 UTC
