### ISSUE TITLE
circular dependency tip does not work

### ISSUE THREAD

**Issue by VerdonTrigance** [dotnet/EntityFramework.Docs#3147] opened 2021-03-10 12:09 UTC
Page https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli
tells us:

> If this causes a circular dependency, you can update the base output path of the migrations project instead:

I did that and it does not work:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
	<ProjectReference Include="..\MsSqlMigration\MsSqlMigration.csproj" />
  </ItemGroup>  
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.12.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.1" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.1" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.0-preview3" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.1.12" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="5.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>
</Project>
```

and migration project is:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
	<BaseOutputPath>..\Backend\bin\</BaseOutputPath>
  </PropertyGroup>  
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Backend\Backend.csproj" />
  </ItemGroup>
</Project>
```

I still get NU1108.

Was it even ever possible to avoid circular dependency by changing output folder? O_o

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment] 2021-03-11 00:31
Remove the `ProjectReference` pointing to the migrations project--having the dll in the output directory of the project is enough for the tooling to work.

**Comment by bricelam** [comment] 2021-03-11 00:35
[Here](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Schemas/TwoProjectMigrations) is a working sample for reference.

The app project:

https://github.com/dotnet/EntityFramework.Docs/blob/cac84d91b91d53085829aa2a3d6f438385a7e19b/samples/core/Schemas/TwoProjectMigrations/WorkerService1/WorkerService1.csproj#L1-L18

The migrations project:

https://github.com/dotnet/EntityFramework.Docs/blob/cac84d91b91d53085829aa2a3d6f438385a7e19b/samples/core/Schemas/TwoProjectMigrations/SqliteMigrations/SqliteMigrations.csproj#L1-L12

**Comment by VerdonTrigance** [comment] 2021-03-11 07:22
> Remove the `ProjectReference` pointing to the migrations project--having the dll in the output directory of the project is enough for the tools to work.

But point 5 in the article tells:

> Add a reference to your migrations project from the startup project.

We should replace this or next phrase:

> If this causes a circular dependency, you can update the base output path of the migrations project instead:

to something like this:

"If this causes a circular dependency, remove the `ProjectReference` and update the base output path of the migrations project instead:"

**Comment by bricelam** [comment] 2021-03-12 19:57
We should do this (and more) as part of #933

**Comment by ajcvickers** [comment] 2021-03-16 18:48
Closing this as a duplicate of #933 where we are tracking improvements to these docs.

**Closed by ajcvickers** 2021-03-16 18:48 UTC
Labels: area-migrations
