### ISSUE TITLE
If index is given a name, two "CreateIndex" are created in the migration

### ISSUE THREAD

**Issue by sturlath** [dotnet/EntityFramework.Docs#3658] opened 2022-01-05 12:20 UTC
If I use fluent API and add an index like this

```charp
modelBuilder.Entity<JobLine>(entity =>
{
    entity.HasIndex(e => e.FileId, "IX_JobLines_FileId");
}
```

the code that gets generated in migrations has two indexes

```charp
  migrationBuilder.CreateIndex(
      name: "IX_JobLines_FileId",
      table: "JobLines",
      column: "FileId",
      unique: true);

 // this extra index gets created
  migrationBuilder.CreateIndex(
      name: "IX_JobLines_FileId1",
      table: "JobLines",
      column: "FileId");
```
but if I skip it like this

```charp
modelBuilder.Entity<JobLine>(entity =>
{
    entity.HasIndex(e => e.FileId);
}
```
the extra one is not created.

So two questions

- Should I even name them (especially if they end up with the same name)
- Is this a bug or am I not understanding the usage?

I'm using EF Core 5.0.6

**Comment by roji** [comment] 2022-01-05 14:13
As in #3659, I cannot reproduce this - with the above I only get one index created.

Please post a full code sample rather than snippets, this would help us investigate.

**Comment by sturlath** [comment] 2022-01-05 14:46
Ok I´ll create an example for this (and the other one) and get back to you.

**Comment by ajcvickers** [comment] 2022-01-18 16:02
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-01-18 16:02 UTC
