### ISSUE TITLE
migration for multi project 

### ISSUE THREAD

**Issue by ekhtiari** [dotnet/EntityFramework.Docs#3702] opened 2022-01-27 07:07 UTC
[Enter feedback here]

if in Solution has several project and several startup project we must use this command on cli to create migrations and update database that miss on this document : 
(this command must run on project that contain dbcontext file )
`dotnet ef migrations add <Name of migration> --startup-project ../MyStartupProjectName`

for update database use this command : 

`dotnet ef database update --startup-project ../MyStartupProjectName`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-01-31 10:54
Duplicate of #933.

**Closed by ajcvickers** 2022-01-31 10:54 UTC
