### ISSUE TITLE
Add an example please

### ISSUE THREAD

**Issue by nbon12** [dotnet/EntityFramework.Docs#2469] opened 2020-06-18 13:09 UTC
As a developer it would be nice to see an example of calling the .Remove method on this page so that I can learn how to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9437a1ec-1ec8-970c-aa5a-321025e6f337
* Version Independent ID: 7f7434ef-0532-4f6d-20ac-a02b2099a192
* Content: [DbContext.Remove Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.remove?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-06-18 15:10
@nbon12 See the docs here: https://docs.microsoft.com/ef/core/saving/basic

Duplicate of #1453.

**Closed by ajcvickers** 2020-06-18 15:10 UTC

**Comment by nbon12** [comment] 2020-06-20 22:26
Thanks!
