### ISSUE TITLE
Bug in the UI

### ISSUE THREAD

**Issue by MohamedOsama911** [dotnet/EntityFramework.Docs#3741] opened 2022-02-20 21:13 UTC
[Enter feedback here]
There is a bug in the UI in " In this article" section where that spot interfere with content in the middle of the page
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 335739cf-c818-c2f1-6f66-5e850bd5c7a7
* Version Independent ID: 8c2c97d5-94d9-baba-1a23-e3cdcdb2e574
* Content: [DbContext Class (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext?view=efcore-6.0#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-02-21 11:53
@MohamedOsama911 I can't see any issue, can you please send a screenshot?

**Comment by MohamedOsama911** [comment] 2022-02-21 18:20
![Screenshot (649)](https://user-images.githubusercontent.com/87633359/155008724-3f9d2fe6-649b-4a7d-b275-bf015cf9e36f.png)

**Comment by roji** [comment] 2022-02-21 19:49
I can't reproduce this either with the latest versions of Chromium or Vivaldi.

**Comment by ajcvickers** [comment] 2022-02-22 09:38
Looks fine for me on Edge and Chrome in Windows.

**Comment by ajcvickers** [comment] 2022-03-01 13:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-03-01 13:03 UTC
