### ISSUE TITLE
FindAsync() now returns ValueTask<T>

### ISSUE THREAD

**Issue by tkurskiev** [dotnet/EntityFramework.Docs#2193] opened 2020-03-18 08:36 UTC
With help of the information, that can be found here:
https://docs.microsoft.com/ru-ru/ef/core/what-is-new/ef-core-3.0/breaking-changes#rtnt

Starting from EF Core 3.0 FindAsync() returns ValueTask&lt;T&gt; and not the Task&lt;T&gt;, this article should be updated I guess?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ff656e-4936-b37c-e1cc-1824aa148ccd
* Version Independent ID: b18f904f-d60c-955b-5aee-b739ffd8fe9f
* Content: [DbContext.FindAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.findasync?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-03-18 14:59
Duplicate of https://github.com/dotnet/EntityFramework.ApiDocs/issues/73

**Closed by ajcvickers** 2020-03-18 14:59 UTC
