### ISSUE TITLE
How do we then test repository?

### ISSUE THREAD

**Issue by iot-crazy** [dotnet/EntityFramework.Docs#3808] opened 2022-04-06 16:26 UTC
[Enter feedback here]
This is a good article and I already follow such a pattern but, this still leaves the LINQ queries themselves untested. How can we test to ensure that the repository layer is indeed obtaining the correct data from the database without an integration test?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Version Independent ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Content: [Choosing a testing strategy - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#repository-pattern)
* Content Source: [entity-framework/core/testing/choosing-a-testing-strategy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/choosing-a-testing-strategy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-04-07 08:56
> How can we test to ensure that the repository layer is indeed obtaining the correct data from the database without an integration test?

Can you elaborate what exactly do you mean? Integration testing usually means testing against your database, so testing that correct data is obtained from the database without involving a database sounds like a contradiction... What exactly are you looking to test here?

**Comment by ajcvickers** [comment] 2022-04-19 11:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-04-19 11:30 UTC
