### ISSUE TITLE
INavigationBase .GetCollectionAccessor exceptions

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/EntityFramework.Docs#3616] opened 2021-12-11 15:26 UTC
Please mention that [GetCollectionAccessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.inavigationbase.getcollectionaccessor) will throw an [InvalidOperationException](https://docs.microsoft.com/en-us/dotnet/api/system.invalidoperationexception) when the type of the navigation property is an array type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a4e1ee9-a3b5-9271-8a50-4b96c77719cd
* Version Independent ID: 1e4c7982-4836-c6f0-924a-86934db1df19
* Content: [INavigationBase Interface (Microsoft.EntityFrameworkCore.Metadata)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.inavigationbase?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata/INavigationBase.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata/INavigationBase.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-12-11 19:54
Duplicate of https://github.com/dotnet/efcore/issues/20086#issuecomment-592704875

**Comment by yecril71pl** [comment] 2021-12-11 20:20
It is not a duplicate. 
* That one: describe exceptions that may be caught.
* This one: describe what not to do or you will get a run time exception.

These use cases are fundamentally different.  Note that it would be much better to catch such errors during build.

**Closed** 2021-12-15 16:23 UTC
