### ISSUE TITLE
Please link Transaction docs in the IDbContextTransaction interface docs

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/EntityFramework.Docs#2832] opened 2020-11-03 16:13 UTC
Hi,

Please link [this](https://docs.microsoft.com/en-us/ef/core/saving/transactions) page to the attached `IDbContextTransaction` (and related) page.

Thank you

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ea8a9e-2bd0-6dd9-e23a-6a77f882cdad
* Version Independent ID: 47d53326-84b5-6ee9-f2e5-f7844cedb570
* Content: [IDbContextTransaction Interface (Microsoft.EntityFrameworkCore.Storage)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.idbcontexttransaction?view=efcore-3.1&source=docs)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Storage/IDbContextTransaction.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Storage/IDbContextTransaction.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-11-06 21:03
Duplicate of https://github.com/dotnet/efcore/issues/17508

**Closed by ajcvickers** 2020-11-06 21:03 UTC
