### ISSUE TITLE
"Design-time services/Using services" sample throws InvalidOperationException

### ISSUE THREAD

**Issue by a2er** [dotnet/EntityFramework.Docs#4454] opened 2023-08-21 20:26 UTC
#### Specific Case
The [sample to request design time services](https://github.com/dotnet/EntityFramework.Docs/blob/6c094b998fcf89041e27dee0f012cdbb2876bb27/samples/core/Miscellaneous/CommandLine/CustomTools.cs) throws an `InvalidOperationException` (when executed with [.NET 6 / ef7](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Miscellaneous/CommandLine/CommandLine.csproj)):
```text
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Design.IAnnotationCodeGenerator' while attempting to activate 'Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsCodeGeneratorDependencies'.
```
---
#### General Case
The [sample to request design time services](https://github.com/dotnet/EntityFramework.Docs/blob/6c094b998fcf89041e27dee0f012cdbb2876bb27/samples/core/Miscellaneous/CommandLine/CustomTools.cs) does not work for all listed services in section `List of services`.

According [my tests](https://github.com/a2er/EfCoreDesignServices) the sample works only for a subset of services:
- **.NET 5:** `IAnnotationCodeGenerator`, `ICSharpHelper`, `IPluralizer`, `IMigrationsCodeGenerator`, `IMigrationsScaffolder`
- **.NET 6-7:** `IPluralizer` and `IScaffoldingModelFactory`
- **.NET 8:** `IModelCodeGenerator`, `IPluralizer`, `IScaffoldingModelFactory`

Other services will return null or throw an exception due to unresolved dependencies.

Comparing the example with [DesignTimeServicesBuilder.Build](https://github.com/dotnet/efcore/blob/9027f96a45fb3bc621a9f601424c534e4ba564b0/src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs#L54-L69) I assume that this is expected behaviour since the provider design-time services are not loaded.

---
#### Long story short
The section `Using services` should mention which services can be used effectively or the public API should get the capabilities to load provider, referenced and implementation design-time services equal to [DesignTimeServicesBuilder.Build](https://github.com/dotnet/efcore/blob/9027f96a45fb3bc621a9f601424c534e4ba564b0/src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs#L54-L69).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2886eabf-4b28-c390-9634-14e623e8ec8e
* Version Independent ID: 1ef0f90d-664c-81f7-ee5d-f67dafce4ed1
* Content: [Design-time services - EF Core](https://learn.microsoft.com/en-us/ef/core/cli/services)
* Content Source: [entity-framework/core/cli/services.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/cli/services.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by seclerp** [comment] 2024-08-27 17:29
I am also facing the exact problem when trying to build IServiceProvider with design-time services. Is there any plan to provide a working API for that?

**Comment by AndriySvyryd** [comment] 2024-09-14 01:53
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/4013 and https://github.com/dotnet/EntityFramework.Docs/issues/3390

**Closed by AndriySvyryd** 2024-09-14 01:53 UTC
Labels: area-tools
