### ISSUE TITLE
Missing documentation about init-only setters and records

### ISSUE THREAD

**Issue by fjallemark** [dotnet/EntityFramework.Docs#2989] opened 2021-01-07 19:20 UTC
I miss how EFCORE handle init-only setters for structs, classes and records.
I also miss documentation about any differences using records instead of classes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc7aedf-6301-7ec7-4f65-81749b1f54c8
* Version Independent ID: d0774ffa-c841-e6df-72de-d7f53c0d6f6f
* Content: [Entity types with constructors - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/constructors)
* Content Source: [entity-framework/core/modeling/constructors.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/constructors.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-01-07 19:30
Duplicate of #2931

**Comment by roji** [comment] 2021-01-07 19:30
Init-only properties should work just like normal properties - EF uses reflection to set properties on entities that it loads, and that works regardless of whether the property has a regular setter or an init-only setter.

In principle, records aren't different from classes. However, records are frequently used for immutable types, and that doesn't work well with EF Core's change tracking mechanism.

@ajcvickers it feels like we've had this discussion frequently enough that it may be worth doing #2931 for 6.0, maybe I'll give it a stab.

**Closed by roji** 2021-01-07 19:30 UTC

**Comment by ajcvickers** [comment] 2021-01-07 19:55
@roji Go for it.
