### ISSUE TITLE
Possible wrong information regarding the repository test pattern

### ISSUE THREAD

**Issue by mirinkinen** [dotnet/EntityFramework.Docs#4402] opened 2023-06-29 10:30 UTC
The table under title 'Overall comparison' claims that using repository pattern you can test raw SQL, transactions, provider-specific translations and exact query behavior. Isn't this wrong since the point of repository pattern is to replace the whole data access interface with mock implementation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Version Independent ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Content: [Choosing a testing strategy - EF Core](https://learn.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy)
* Content Source: [entity-framework/core/testing/choosing-a-testing-strategy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/choosing-a-testing-strategy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2023-06-29 14:20
@mirinkinen the point here is that using a repository makes it possible to unit-test code that uses raw SQL in production; in other words, you abstract the raw SQL query behind the repository pattern, so that you can swap the implementation when testing and mock it. Doing so isn't possible when using the other methods (e.g. using EF with a database fake such as InMemory/SQLite).

However, it isn't the first time we see this confusion, see #4303 for a very similar issue. I'll close this as a duplicate of that one.

**Comment by roji** [comment] 2023-06-29 14:20
Duplicate of #4303

**Closed by roji** 2023-06-29 14:20 UTC
