### ISSUE TITLE
Table Per Concrete - Performance

### ISSUE THREAD

**Issue by skywalkerisnull** [dotnet/EntityFramework.Docs#3854] opened 2022-05-09 05:56 UTC
This document describes how to do a Table Per Concrete: https://docs.microsoft.com/en-gb/ef/ef6/modeling/code-first/fluent/types-and-properties#mapping-the-table-per-concrete-class-tpc-inheritance

But this page is missing the details on the performance impact of such a choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb8ded7-f955-4e7e-c711-722af98c84d7
* Version Independent ID: 9acdd9fa-8c8f-7548-83bd-8ff966d78fc8
* Content: [Modeling for Performance - EF Core](https://docs.microsoft.com/en-us/ef/core/performance/modeling-for-performance#inheritance-mapping)
* Content Source: [entity-framework/core/performance/modeling-for-performance.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/modeling-for-performance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-05-09 08:23
@skywalkerisnull TPC support hasn't yet been fully implemented, and therefore isn't yet documented - keeping this open to track updating the perf section for 7.0.

@skywalkerisnull note that your link above points to the EF6 page - we won't be updating that, only the EF Core docs.

**Comment by roji** [comment] 2022-06-18 15:01
Duplicate of #3890

**Closed by roji** 2022-06-18 15:01 UTC
Labels: area-model-building
