### ISSUE TITLE
Connection String Argument Support

### ISSUE THREAD

**Issue by Your3Wishes** [dotnet/EntityFramework.Docs#2472] opened 2020-06-22 14:12 UTC
Does EF Core 3.x actually support the -connection string argument on the Update-Database command? Seems a bit misleading to include that on this page without some kind of disclaimer. I thought this was something new being added to EF Core 5. Hopefully I'm wrong though, I haven't been able to get EF Core 3.x and updated PCM tools to support it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2020-06-22 16:31
Duplicate of #2470

**Closed by ajcvickers** 2020-06-22 16:31 UTC
