### ISSUE TITLE
Error on Add-Migration InitialCreate

### ISSUE THREAD

**Issue by JakeSlade05** [dotnet/EntityFramework.Docs#2300] opened 2020-04-18 14:29 UTC
The current CSharpHelper cannot scaffold literals of type 'System.Collections.Generic.SortedDictionary`2[System.ValueTuple`2[System.String,System.String],Microsoft.EntityFrameworkCore.Metadata.Internal.Table]'. Configure your services to use one that can.
?? How do I do this??????? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=visual-studio#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-04-20 16:02
@JakeSlade05 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-05-01 16:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-05-01 16:28 UTC
