### ISSUE TITLE
no difference between RESTRICT and NO ACTION

### ISSUE THREAD

**Issue by sdudnic** [dotnet/EntityFramework.Docs#3318] opened 2021-07-08 13:06 UTC
The Description of both of the enumeration ("restrict" and "no action") are literally the same.

see also [this SO question](https://stackoverflow.com/questions/64259612/what-is-different-between-deletebehavior-noaction-and-deletebehavior-restrict-in)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment] 2021-07-08 18:50
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2212

**Closed by AndriySvyryd** 2021-07-08 18:50 UTC

**Comment by sdudnic** [comment] 2021-07-09 12:28
@AndriySvyryd please make difference between a question, and a call to action. The documentation should usually be clear, and not leave question like this. If an answer is provided, that answer should be reflected in the documentation. I would not close this issue until a change is made on the corresponding documentation page.
