### ISSUE TITLE
Unrecognized option '--namespace'

### ISSUE THREAD

**Issue by lakani** [dotnet/EntityFramework.Docs#2356] opened 2020-05-03 00:24 UTC
i'm getting the below error while trying to generate code from Database
Unrecognized option '--namespace'

PS D:\Projects\HealthVault&gt; ls

    Directory: D:\Projects\HealthVault

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           4/25/2020 11:58 PM                .vscode
d----            5/3/2020  3:08 AM                HealthVault.Client 
d----            5/3/2020  3:08 AM                HealthVault.Model  
d----            5/3/2020  3:08 AM                HealthVault.Service
-a---            5/3/2020  3:20 AM           1061 build_model.ps1    
-a---           4/26/2020 11:46 PM           1761 HealthVault.sln    

PS D:\Projects\HealthVault&gt; dotnet ef dbcontext scaffold "Server=localhost;Database=HealthVault;UID=sa;password=get@get1" Microsoft.EntityFrameworkCore.SqlServer --namespace "HealthVault.EF" -f  --use-database-names --project HealthVault.Client -o "..\HealthVault.Model" --context-dir "..\HealthVault.Service"     

Build started...
Build succeeded.
Specify --help for a list of available options and commands.
Unrecognized option '--namespace'
PS D:\Projects\HealthVault&gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding#feedback)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2020-05-04 16:58
Duplicate of #2357

**Closed by ajcvickers** 2020-05-04 16:58 UTC
