### ISSUE TITLE
Wrong method name in the sentence.

### ISSUE THREAD

**Issue by reymonreyes** [dotnet/EntityFramework.Docs#4364] opened 2023-05-29 12:31 UTC
[Enter feedback here]
`DbSet<TEntity>.Add` was used instead of `DbSet<TEntity>.Remove` in the sentence. See attached screenshot below.
![Screenshot_197](https://github.com/dotnet/EntityFramework.Docs/assets/476682/5bbb494c-a31c-4e1b-84cd-7ac514ca5f39)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23f8db8b-8ee6-86c9-7cb2-b5802214ec13
* Version Independent ID: b959839c-684e-5d60-650e-0af17c971c79
* Content: [Basic SaveChanges - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/basic)
* Content Source: [entity-framework/core/saving/basic.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/basic.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2023-05-29 22:16
Duplicate of #4362

**Comment by roji** [comment] 2023-05-29 22:16
Already fixed, needs to be pushed live.

**Closed by roji** 2023-05-29 22:16 UTC
