### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by gerd13** [dotnet/EntityFramework.Docs#2290] opened 2020-04-15 19:51 UTC
Some commands are not working on my machine:
`dotnet tool install --global dotnet-ef`
I use dotnet v3.1.2 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#feedback)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by AndriySvyryd** [comment] 2020-04-16 23:16
@gerd13 What's the error that you get?

**Comment by ajcvickers** [comment] 2020-04-27 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-04-27 16:37 UTC
