### ISSUE TITLE
dead link on the page

### ISSUE THREAD

**Issue by anirugu** [dotnet/EntityFramework.Docs#3218] opened 2021-04-21 18:13 UTC
[Enter feedback here]

 https://ak.ms/AA6h122 should be replaced with  https://aka.ms/AA6h122.

When I click on report this, I see this github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml

I clone it and see it's not there, Can anyone guide me does it coming from metadata or somewhere else. I clone that repos and doesn't find the url in the file (which I seen when raising this issue).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21434a2-9f80-b04b-f8d7-b63eee000407
* Version Independent ID: 78f0bdb8-6553-a7cf-450f-167d522160d0
* Content: [SqlServerDbContextOptionsBuilder.UseRowNumberForPaging Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.sqlserverdbcontextoptionsbuilder.userownumberforpaging?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-04-21 18:57
Duplicate of #3206

**Comment by roji** [comment] 2021-04-21 18:57
Thanks - this was already fixed but is not yet visible on the live site.

**Closed by roji** 2021-04-21 18:57 UTC

**Comment by smitpatel** [comment] 2021-04-21 20:16
Updated live site.
