### ISSUE TITLE
Missing description of which Exception is thrown

### ISSUE THREAD

**Issue by Kurt17P** [dotnet/EntityFramework.Docs#2467] opened 2020-06-17 09:33 UTC
It seems the information about which exact exception is thrown by `SingleOrDefaultAsync` when duplicate entries are found is missing from the documentation. IntelliSense also does not suggest which exception is thrown. Maybe it is common knowledge where to look up such information, but this common knowledge did not reach me (yet). 

When I test, it seems a `System.InvalidOperationException: Enumerator failed to MoveNextAsync.` is thrown. Despite the fact that I find the error message not descriptive, I can catch a more specialized exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d5a5fa-c203-fef3-e2b6-a51bd4f2a175
* Version Independent ID: 294bcecd-d216-9e7c-85f2-09d375248627
* Content: [EntityFrameworkQueryableExtensions.SingleOrDefaultAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.singleordefaultasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync%60%601);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-06-17 15:59
Duplicate of https://github.com/dotnet/efcore/issues/20086

**Closed by ajcvickers** 2020-06-17 15:59 UTC
