### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by RossAnderson55** [dotnet/EntityFramework.Docs#2914] opened 2020-11-29 04:07 UTC
I am getting an error that the database table Blogs does not exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment] 2020-11-29 05:07
What was the output from
```
dotnet tool install --global dotnet-ef
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet ef migrations add InitialCreate
dotnet ef database update
```

Maybe you copy/pasted and didn't actually run `dotnet ef database update` ?

**Comment by ajcvickers** [comment] 2020-12-07 16:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-12-07 16:46 UTC

**Comment by tmfink10** [comment] 2021-01-11 11:48
I receive the same error. I also verified that I updated the database by trying again and receiving:
Build started...
Build succeeded.
No migrations were applied. The database is already up to date.
Done.

It looks like Blogs should be created in the migration, but I'm also doing this intro tutorial for a reason... ;-)

`namespace EFGetStarted.Migrations
{
    [DbContext(typeof(Program.BloggingContext))]
    [Migration("20210111112324_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EFGetStarted.Program+Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EFGetStarted.Program+Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFGetStarted.Program+Post", b =>
                {
                    b.HasOne("EFGetStarted.Program+Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EFGetStarted.Program+Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
`

**Comment by ywwyeu** [comment] 2021-01-15 11:18
Try using a absolute path to your database   ("Data Source = c:\\Yourfolder\\blogging.db")
