### ISSUE TITLE
Timespan EF Queries

### ISSUE THREAD

**Issue by hypertrends** [dotnet/EntityFramework.Docs#2616] opened 2020-09-06 19:16 UTC
Hello,
We are wondering what the querying would look like for querying timespans using the TimeSpan Converters. We are using Postgresql using npgsql and are unable to identify the right way to query this data. Can you please amend this document with any possible examples?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2020-09-07 22:04
Duplicate of #10434

**Comment by roji** [comment] 2020-09-07 22:09
EF doesn't currently support translations when value converters are configured - see https://github.com/dotnet/efcore/issues/10434.

However, note that EFCore.PG translates some basic operations for TimeSpan, when it is mapped without a value converter (i.e. to a PG interval). If you open an issue on [the EFCore.PG repo](https://github.com/npgsql/efcore.pg/issues) I can try to assist more.

**Closed** 2020-09-08 15:36 UTC
Labels: closed-duplicate
