### ISSUE TITLE
Use of Async Await and parallel while doing CRUD using EF 

### ISSUE THREAD

**Issue by sameersayani** [dotnet/EntityFramework.Docs#2080] opened 2020-01-31 02:32 UTC
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by ajcvickers** [comment] 2020-02-12 21:58
@sameersayani Please provide some more details on exactly what you are asking about here.

**Comment by ajcvickers** [comment] 2020-02-24 17:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-02-24 17:49 UTC
