### ISSUE TITLE
Needs details

### ISSUE THREAD

**Issue by musakasim** [dotnet/EntityFramework.Docs#2512] opened 2020-07-13 14:35 UTC
Needs more explanation, any perks or disadvantages? Or It is just Calling Add() in a for loop?
Any remarks on AutoDetectChangesEnabled behaviour(disabling-enabling it)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21c7ccf0-e002-3ec1-3936-5fbbe79d80f6
* Version Independent ID: a58ebe42-467c-acf3-9c51-513e6dc8fec0
* Content: [DbContext.AddRange Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addrange?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-07-13 20:22
Duplicate of https://github.com/dotnet/efcore/issues/17508

**Closed by ajcvickers** 2020-07-13 20:22 UTC
