### ISSUE TITLE
Does not help with implementing basic OOP

### ISSUE THREAD

**Issue by DimitryNechaev** [dotnet/EntityFramework.Docs#2820] opened 2020-10-30 01:55 UTC
This article implies that if I have 10 entities which have the same field "IsDeleted" I need to copy-paste the filter 10 times.
Basic OOP expects to have a single base entity with the field and the rule applied on the base level.

At the moment I greatly struggle with EF Core trying to do exactly this and nowhere can find applicable article.
In my case a large number of 3rd pty tables having StatusId field, which I mage though basic abstract class HasStatus.

The best so far is that I manage to enumarate though all entities but can't apply a filter, as there is no generic to accept the base type. HasQueryFilter accepts LambdaExpression, which is a bummer.

            foreach (var entity in modelBuilder.Model.FindLeastDerivedEntityTypes(typeof(HasStatus)))
            {
                modelBuilder.Entity(entity.ClrType)
                    .HasQueryFilter(t => t.StatusID == 1);
           }
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/filters.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @maumar
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-10-30 22:50
@DimitryNechaev This is one of the usability issues around query filters that are being tracked on https://github.com/dotnet/efcore/issues/21459. Closing this as a duplicate of that issue, with a reference to here.

**Closed by ajcvickers** 2020-10-30 22:50 UTC

**Comment by snappyfoo** [comment] 2021-03-21 00:14
FWIW you can build the expression doing something like so:

```C#
foreach (var entity in modelBuilder.Model.FindLeastDerivedEntityTypes(typeof(HasStatus)))
{
    var statusIdProperty = entity.FindProperty(nameof(HasStatus.StatusID)).PropertyInfo;
  
    var parameterExpression = Expression.Parameter(entity.ClrType);
    var propertyExpression = Expression.Property(parameterExpression, statusIdProperty);
    var constExpression = Expression.Constant(1);

    var equalExpression = Expression.Equal(propertyExpression, constExpression));
    
    var filter = Expression.Lambda(equalExpression, parameterExpression);

    modelBuilder.Entity(entity.ClrType).HasQueryFilter(filter);
}
```
