### ISSUE TITLE
Add method-based versions of the example queries

### ISSUE THREAD

**Issue by IanKemp** [dotnet/EntityFramework.Docs#3563] opened 2021-11-16 11:29 UTC
Currently there are only query expression examples; corresponding method-based syntax examples would help for people who are more familiar with the latter syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1acf84-126c-f01d-b39a-ab077819351f
* Version Independent ID: 5d3bdd6d-ad0e-e306-5aef-0d5adea892b6
* Content: [Complex Query Operators - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators)
* Content Source: [entity-framework/core/querying/complex-query-operators.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/complex-query-operators.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment] 2021-11-16 16:24
Duplicate of #1383

**Closed by smitpatel** 2021-11-16 16:24 UTC
