### ISSUE TITLE
Spatial Geometry is not working in EF core asp.net core 3.1

### ISSUE THREAD

**Issue by maharasa** [dotnet/EntityFramework.Docs#2928] opened 2020-12-07 15:52 UTC
I am using asp.net core 3.1 application with EF core
Microsoft.EntityFrameworkCore.SqlServer Version="5.0.0"
Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite Version="5.0.0"
Microsoft.EntityFrameworkCore.Tools" Version="5.0.0"

I added the following code in dbcontext Onconfigure method
optionsBuilder.UseSqlServer(GetConnectionString(), x => x.UseNetTopologySuite());

I added model property 
public Geometry Geom { get; set; }

when I run project in Get API I am getting this errror
"**No suitable constructor was found for entity type 'CoordinateSystem'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'epsgId', 'topology' in 'CoordinateSystem(int epsgId, string name, Topology topology)'.**"

Please help on this I am facing this issue more then a week but not able to solve error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dcf82b-f177-e91b-96a5-67f2f57bd6c4
* Version Independent ID: 89c0803f-570f-07a6-6dc2-285678712c86
* Content: [Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/spatial)
* Content Source: [entity-framework/core/modeling/spatial.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-12-07 17:18
@maharasa I am not able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-12-15 17:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-12-15 17:27 UTC
