### ISSUE TITLE
example how to save multiple records added in an entity

### ISSUE THREAD

**Issue by bvergara023** [dotnet/EntityFramework.Docs#2784] opened 2020-10-16 18:51 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6449c42e-0016-d50e-9af5-db14e7ce4f3e
* Version Independent ID: 114b3c81-8bb0-a9a8-e449-80162dc9cefd
* Content: [DbSet.AddRange(IEnumerable) Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbset.addrange?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/DbSet.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbSet.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by roji** [comment] 2020-10-17 08:01
Can you provide more detail on what you're looking for here?

**Comment by ajcvickers** [comment] 2020-10-26 16:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-10-26 16:49 UTC
