### ISSUE TITLE
The instance of entity type 'UnitSkill' cannot be tracked because another instance with the same key value for entity Name is already being tracked. 

### ISSUE THREAD

**Issue by santosh2812** [dotnet/EntityFramework.Docs#2336] opened 2020-04-28 21:18 UTC
[My Requirement :

I have 3 tables in My DB 
1. Units 
2. Skills
3. UnitSkill

Now I Have 2 UI screen from where we add value in DB- First is Skills UI, here the Units are not created. Skills are created as Master list in DB, Which will be used in Multiselect Dropdown to choose Skills to be associated with Unit. vice versa also can happen.

**What I follow :**
have dataModel of all three etity. and have created Repository of only 2 Entity (Units and Skill) as the other one is the relation entity.
```json
    {
    "name": "Sanskrit Varnamal grade 1",
    "durationInDays": 10,
    "courseId": "b0ffcb3c-d050-4d53-8da8-12c8039f93c3",
     "unitSkills": [
    {
      "id": "bdf5456e-3de4-4269-a09c-4feb5362268c",
    },
    {
      "id": "c99cf918-2a47-4146-8461-7ba5c2efda83",
    }]
```

Now the action method of API-

```C#
    public async Task<IActionResult> Post([FromBody] CreateUnitVM Model)
         {
            var DataModel = _mapper.Map<Unit>(Model);
            DataModel.CreatedAt = DateTime.Now;
            DataModel.UpdatedAt = DateTime.Now;
            foreach (var item in Model.UnitSkills)
            {

                DataModel.UnitSkills.Add(new UnitSkill
                {
                    SkillId = item.Id
                   

                });
            }
           
            //DataModel.CreatedBy=
            
            var result = await _UnitRepository.CreateAsync(DataModel);
            
            return Ok(result);
        }
```
But the above code throws error,
The instance of entity type 'UnitSkill' cannot be tracked because another instance with the same key value for {'SkillId', 'UnitId'} is already being tracked. When attaching existing entities, ensure that only one  entity instance with a given key value is attached. Consider using 
 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
Now after reading other posts I assume that this is not the right approach, Please guide me.

Thanks
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0fb981-4dec-7ff7-817b-6606f620b875
* Version Independent ID: c7517e7d-f011-a24c-53da-913771913998
* Content: [Saving Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/related-data)
* Content Source: [entity-framework/core/saving/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-04-29 15:31
There isn't enough code shown here to properly understand the interaction with EF. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by santosh2812** [comment] 2020-04-30 14:09
Hi @ajcvickers ,
The code which I have posted is part of a large project, Need send you the running sample project. Mean while its related to Many To Many Relation, I will try to elaborate my Issue and the exception : So that if you would have link or sample we could share.
I have three entity - 1. Unit 2. Skill and 3 UnitSkill this the relation or intermediate table for storing the relation. 
Now I have a separate UI for Skill creation, This means Skill is created very first. 
When we come to create Unit then the skills are shown in a dropdown list -for multi select. 
What I want -when I am creating UNIT that time  only I could be able to create the relation. 
If you see the Json which I am posting to the action having multiple Id in SKILLUnit part which is the Skill Id. 
On action, am assigning in the related entity, that leads to throw the above exception. 

Have tried another approach like fetching the skill from DB and then attaching the same in the Unit Model Navigation part.
Hope I am able to state my problem.

**Comment by ajcvickers** [comment] 2020-05-01 16:33
@santosh2812 There isn't enough here to properly understand the interaction with EF. I think we're going to need runnable code to fully investigate.

**Comment by ajcvickers** [comment] 2020-05-08 15:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-05-08 15:28 UTC
