### ISSUE TITLE
Not helpful at all!

### ISSUE THREAD

**Issue by Gergeli96** [dotnet/EntityFramework.Docs#4534] opened 2023-10-24 16:10 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6dc1fa-269e-bd35-6a97-b3f409b13a4c
* Version Independent ID: 183d4acf-2f33-55e1-1e82-58a585690c1f
* Content: [RelationalStrings.DataOperationNoTable(Object) Method (Microsoft.EntityFrameworkCore.Diagnostics)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.relationalstrings.dataoperationnotable?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/RelationalStrings.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/RelationalStrings.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-11-08 20:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-11-08 20:27 UTC
