### ISSUE TITLE
Should mention IMaterializationInterceptor as well.

### ISSUE THREAD

**Issue by voroninp** [dotnet/EntityFramework.Docs#4545] opened 2023-11-06 10:08 UTC
.NET EF Core 7.0 added support for `IMaterializationInterceptor`, it should be mentioned in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d03fe111-e320-1c4f-1d39-b9ff485c2ac8
* Version Independent ID: c80b6f7c-623d-036a-e911-720bd56254b3
* Content: [IInterceptor Interface (Microsoft.EntityFrameworkCore.Diagnostics)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.iinterceptor?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/IInterceptor.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/IInterceptor.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-11-06 10:09
Duplicate of #4417

**Closed by ajcvickers** 2023-11-06 10:09 UTC

**Comment by voroninp** [comment] 2023-11-06 10:11
@ajcvickers , do you ever sleep, guys ? =)

**Comment by ajcvickers** [comment] 2023-11-06 10:14
If I said no, we don't sleep, would that then excuse us from having not yet documented this feature? 😉

**Comment by voroninp** [comment] 2023-11-06 10:19
Well, limited capacity is still a limited capacity. Unless you have a superpower of extending day beyond 24h.
I may disagree with priorities assigned to various issues =P, but I cannot blame you for not doing everything at once.
