### ISSUE TITLE
need more explanation in "Joining relationships configuration"

### ISSUE THREAD

**Issue by TomasB** [dotnet/EntityFramework.Docs#3686] opened 2022-01-19 21:13 UTC
"Joining relationships configuration" section doesn't have enough information.
After reading and going through sample provided in "Join entity type configuration", it's absolutely not clear what is the point of "Joining relationships configuration" section, why one would use it instead of sample provided in "Joining relationships configuration"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#other-relationship-patterns)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-01-24 13:53
Duplicate of #3648.

**Closed** 2022-01-28 16:20 UTC
Labels: closed-duplicate
