### ISSUE TITLE
Upon deletion of a child table entries on search parent record

### ISSUE THREAD

**Issue by urskris123** [dotnet/EntityFramework.Docs#3125] opened 2021-03-02 13:18 UTC
[Enter feedback here]

When a child records are found existing based on a parent record and a removerange issued will set the state of child table to Deleted and also mark the state of the parent record to deleted. To not let happen we need to explicitly set the state of the parent entry to Modified

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130521ba-2943-c640-4190-7e22af37e154
* Version Independent ID: c31908e9-2836-8efd-5df6-e9dc5b5a9a5f
* Content: [Working with entity states - EF6](https://docs.microsoft.com/en-us/ef/ef6/saving/change-tracking/entity-state)
* Content Source: [entity-framework/ef6/saving/change-tracking/entity-state.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/saving/change-tracking/entity-state.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-03-09 16:23
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-03-19 16:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-03-19 16:47 UTC
