### ISSUE TITLE
Incorrect example for Split Queries

### ISSUE THREAD

**Issue by jbfraser1** [dotnet/EntityFramework.Docs#2670] opened 2020-09-20 02:32 UTC
In the EF 5 docs page, this example shows up twices:
```
using (var context = new SplitQueriesBloggingContext())
{
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
        .AsSingleQuery()
        .ToList();
}

```

I'm pretty sure the first instance of this example code, in the section **Split Queries** should be something like:
```
using (var context = new SplitQueriesBloggingContext())
{
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
        .AsSplitQuery()
        .ToList();
}

```

That command makes more sense in this context, and from some (admittedly limited) experiments seems to be the right command to allow EF to avoid the single query monstrosities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a3ce6e-43ab-e0af-01b3-a82fdaf3cb31
* Version Independent ID: 320e7305-e0a3-a1c6-77f2-1d3029b660b1
* Content: [Eager Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager)
* Content Source: [entity-framework/core/querying/related-data/eager.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data/eager.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2020-09-21 09:30
Duplicate of #2659

**Comment by roji** [comment] 2020-09-21 09:31
@smitpatel can we do a push to live?

**Closed** 2020-09-21 09:31 UTC
Labels: closed-duplicate
