### ISSUE TITLE
On Delete Behavior Documentation Concern

### ISSUE THREAD

**Issue by MGhandour92** [dotnet/EntityFramework.Docs#2645] opened 2020-09-15 14:57 UTC
I can't see the difference between [Restrict, NoAction], I think there is  a mistake in the documentation. Which one will make no effect when deleting the parent Entity?

I want to know which option will leave the data with no change, and what is the difference between the options with Client prefix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-09-15 16:54
There is no practical difference between Restrict and NoAction. Some databases may choose when to check constraints differently, but that should rarely have any functional impact.

Duplicate of #473

**Comment by MGhandour92** [comment] 2020-09-16 05:59
Forget the difference, it is not right what is written:

"the values of foreign key properties in dependent entities are set to null when the related principal is deleted"
"If a property cannot be set to null because it is not a nullable type, then an exception will be thrown when SaveChanges() is called."

NoAction or Restrict, should leave the dependent entities' value

**Comment by ajcvickers** [comment] 2020-09-18 16:59
@MGhandour92 In what specific situation do you not want EF to change the FK value and why?

**Closed** 2020-09-28 16:23 UTC
Labels: closed-duplicate
