### ISSUE TITLE
Update information on the new Bulk updates method in the Efficient Updating section

### ISSUE THREAD

**Issue by Yousif-FJ** [dotnet/EntityFramework.Docs#4178] opened 2022-12-07 13:22 UTC
This page Efficient Updating include outdated information like "Unfortunately, EF doesn't currently provide APIs for performing bulk updates. Until these are introduced, you can use raw SQL to perform the operation where performance is sensitive". New documentation for ExecuteUpdate are needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f37e820a-137f-92c9-6662-06fafeac097a
* Version Independent ID: 0df73aed-692f-0e53-7562-ed3d8b89c6df
* Content: [Efficient Updating - EF Core](https://learn.microsoft.com/en-us/ef/core/performance/efficient-updating)
* Content Source: [entity-framework/core/performance/efficient-updating.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/efficient-updating.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-12-07 13:28
Duplicate of #4032

**Closed by roji** 2022-12-07 13:28 UTC
