### ISSUE TITLE
Misleading or out of date

### ISSUE THREAD

**Issue by ADCJustinH** [dotnet/EntityFramework.Docs#2084] opened 2020-01-31 19:22 UTC
"You can also tell the tools how to create your DbContext by implementing the IDesignTimeDbContextFactory&lt;TContext&gt; interface: If a class implementing this interface is found in either the same project as the derived DbContext or in the application's startup project, the tools bypass the other ways of creating the DbContext and use the design-time factory instead." -- This no longer appears to be true when working with 3.1; DbContext is created according to service registration in startup and IDesignTimeDbContextFactory is ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa64390-1232-8dd3-f170-7d5c68e29ad9
* Version Independent ID: 245bbba8-3102-4a66-15eb-650e05eb9e62
* Content: [Design-time DbContext Creation - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation#feedback)
* Content Source: [entity-framework/core/miscellaneous/cli/dbcontext-creation.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dbcontext-creation.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment] 2020-02-05 23:12
That sounds like a bug. Could you share a repro so we can investigate? Note, even with an IDesignTimeDbContextFactory, the tools still try to build the application service provider to ***discover*** which DbContext types are available, but the context is still *instantiated* using the design-time factory.

**Comment by ajcvickers** [comment] 2020-02-19 21:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-02-19 21:10 UTC
