### ISSUE TITLE
"Overriding value generation" section is confusing

### ISSUE THREAD

**Issue by IanKemp** [dotnet/EntityFramework.Docs#3398] opened 2021-08-24 13:01 UTC
It states:

> To override value generation with an explicit value, simply set the property to any value that is not the CLR default value for that property's type (null for string, 0 for int, Guid.Empty for Guid, etc.).

What it is saying that you **shouldn't** set the property to null/0/Guid.Empty, you should set it to the actual value you want. So why even mention the default value bit? It's unnecessary and confusing. Better text would be:

> To override value generation with an explicit value, simply set the property to the value you require. You cannot use a property type's default value (null for string, 0 for int, Guid.Empty for Guid, etc.) in this manner, as Entity Framework interprets these values as "property not populated" and will thus perform its standard behaviour of generating them at runtime.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-08-25 07:59
@IanKemp We looked at this in triage and the new text doesn't seem clearer to us. Can you try to explain again what it is specifically that you are attempting to clarify in the original text?

**Comment by ajcvickers** [comment] 2021-09-03 16:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-09-03 16:14 UTC
