### ISSUE TITLE
Inconsistency initializer List<T> in entity

### ISSUE THREAD

**Issue by Bezz242** [dotnet/EntityFramework.Docs#4512] opened 2023-10-05 12:22 UTC
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

Hi, 

Ik looks like there is an inconsistency between the md files and the code. I was looking up the best practice for initializing a List<T> navigation property. Should one leave it `null` or initialize with `new();`?

The md files show `public virtual List<Post> Posts { get; set; }`, but the code shows `public virtual List<Post> Posts { get; } = new();`.

Shouldn't be this consistent? And if so, which way is best?

Cheers, B.

**Comment by ajcvickers** [comment] 2023-10-05 12:24
@Bezz242 Please post a link to the doc page you are looking at.

**Comment by Bezz242** [comment] 2023-10-05 13:03
Indeed, I should have done this.

https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Miscellaneous/NewInEFCore8/BlogsContext.cs
https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/migrations/automatic.md

Although I also found
https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Performance/Other/LazyLoading/LazyBloggingContext.cs

Maybe my knowledge on when to initialize List<T> on entities falls short. I, for one, would prefer to initialize with `new()` as I would figure it dramatically lowers chances of null pointer exceptions.

**Comment by ajcvickers** [comment] 2023-10-09 11:21
@Bezz242 

> Ik looks like there is an inconsistency between the md files and the code. 

Where are you seeing this? You linked three unrelated files. Is there a markdown file with a corresponding associated code file where the markdown shows something different than the code?

**Comment by ajcvickers** [comment] 2023-10-25 19:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-10-25 19:37 UTC
