### ISSUE TITLE
Set up relationship between a view and table

### ISSUE THREAD

**Issue by iBolski** [dotnet/EntityFramework.Docs#2386] opened 2020-05-15 12:25 UTC
We have a setup where we have a table that retrieves certain information from a view that is set up in a different schema in Oracle. That information is read only but the table entity has a many to one relationship to that view. 
For example, the table is CAP_ZONE. Each CAP_ZONE must belong to one and only one VALID_RTO (the view). But each VALID_RTO record can be assigned to zero or more CAP_ZONE records.

CAP_ZONE table
cap_zone_id NUMBER(10)
cap_name VARCHAR2(25)
rto_id NUMBER(10)     &lt;--- "FK" back to the VALID_RTO table

VALID_RTO view
rto_id NUMBER(10)
rto_name VARCHAR2(10)
rto_descroption VARCHAR2(25)

How would I set up my classes and the DbContext so that:

1. In CAP_ZONE, it references the one VALID_RTO record to get things such as the RTO Name, Description, etc.
2. In the VALID_RTO class, it can pull back all CAP_ZONE records that are tied to that specific VALID_RTO record.

VALID_RTO -------o&lt; CAP_ZONE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key&source=docs#feedback)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-05-15 18:50
@iBolski You should be able to map and entity type to CAP_ZONE and an entity type to VALID_RTO and setup the relationship between them in the normal way. If this isn't working, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-05-29 18:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-05-29 18:59 UTC
