### ISSUE TITLE
How to specify version of SqlServer?

### ISSUE THREAD

**Issue by herrbehn** [dotnet/EntityFramework.Docs#2663] opened 2020-09-18 12:10 UTC
Hi. When using the Script-Migration command, we get sql scripts that do not work on the production server as this one is not the newest.
Is there a way to specify which version of Sql Server the produced SQL migrations script should work on?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6d4d37-afad-f18c-0deb-89fc57539e29
* Version Independent ID: 011c9d25-c0ff-61a9-5467-ed952d457d89
* Content: [SqlServerDbContextOptionsBuilder Class (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.sqlserverdbcontextoptionsbuilder?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by roji** [comment] 2020-09-18 14:54
What version is your production SQL Server? Can you post the relevant part of the SQL migration script and the error you get?

**Comment by ajcvickers** [comment] 2020-09-18 15:38
Duplicate of #2664

**Closed by ajcvickers** 2020-09-18 15:38 UTC
