### ISSUE TITLE
Split query generation/docs [possible repeat]

### ISSUE THREAD

**Issue by DickBaker** [dotnet/EntityFramework.Docs#4046] opened 2022-09-20 18:47 UTC
1. the code examples will bring back all the Blogs & Posts rows. Better that examples have a WHERE Rating>=4 or somesuch to show how that will also be present in the 2nd SELECT split.
2. the "cartesian explosion" duplicates only applies when querying Posts with an INCLUDE("Blogs") that will have dups of Blogs with multiple Posts, so I would suggest you revise the examples given.
3. surely the EF code generation should impose a DISTINCT in the split statements to suppress such dups?
4. I am surprised that the generated split code shown uses the b.BlogId and not the p.BlogId - yes I know they are the same per the ON clause but it rankles when you are really looking for all the p.* fields to match the EF entity definition [just requires more brain-cycles to validate the resulant match!]

Apologies if this shows up as a repeat as I can't see Issue against my Participating filter. Maybe I never hit the Submit button [brain fade] or EF team summarily Closed it?!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-09-20 19:39
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/4044

**Closed by roji** 2022-09-20 19:39 UTC
