### ISSUE TITLE
Instructions out of date and do not work

### ISSUE THREAD

**Issue by Nepomuceno** [dotnet/EntityFramework.Docs#3404] opened 2021-08-27 03:25 UTC
The instructions on this page are out of date and do not work even if you follow the step by step

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b011c7a-3534-78e3-b491-addd96fb5ba1
* Version Independent ID: 371826c5-3ef2-4eef-32e9-d55c777cd9d3
* Content: [Migrations with Multiple Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/providers.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/providers.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-09-03 16:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-09-03 16:14 UTC

**Comment by khalifima** [comment] 2021-10-01 15:28
Following your guide to produce the migrations and after creating the first migration with sqlite I cannot create a migration with the same name with another provider I get the error **The name 'Initial' is used by an existing migration.**

**Comment by roji** [comment] 2021-10-01 16:07
@khalifima you probably want to read the docs on [migrations with multiple providers](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli). If you're still running into trouble, can you please post detailed, step-by-step instructions on what your doing? For example, which method are you using to manage migrations - multiple context types, or one?
