### ISSUE TITLE
Local Tools Manifest File docs reference

### ISSUE THREAD

**Issue by kenleese** [dotnet/EntityFramework.Docs#2537] opened 2020-07-27 10:24 UTC
Consider replacing the "local tools manifest file" link (which currently directs to an issue thread) with a reference to the more recent docs [https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool)

Thank you for generally clear and useful documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#ef-core-3x)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment] 2020-09-04 22:56
Duplicate of #2144

**Closed by bricelam** 2020-09-04 22:56 UTC
Labels: area-tools, type-correctness
