### ISSUE TITLE
Document how to control environment when using tools

### ISSUE THREAD

**Issue by ParthiKarnan** [dotnet/EntityFramework.Docs#1359] opened 2019-03-14 19:55 UTC
I'm creating a console application using .net core 2.2 with EF Core 2.2.2. Here I'm struggling to maintain Azure SQL Server connection strings dynamically based on the Environment Variable i.e Dev, stage and Prod environment. The connection strings are maintained separate appsettings.(Environment).json files. So I need to get the connection string from the appsetting.(Environment).json file and pass it to the optionsBuilder.UseSqlServer("Azure SQL DB Connection") function  when I run my console application.  Please help me to resolve this issue.

appsettings.Dev.json
`
{
   "Database": {
    "ConnectionString": "Server=xxxxxxxxxx.database.windows.net,1433;Database=qualcontract;User Id=xxxxxx;Password=xxxxxxxx"
  }
}
`
 
I have not seen like this example in MS document.

Thanks in advance,
Parthi Karnan

**Comment by Rick-Anderson** [comment] 2020-09-17 01:11
duplicate of #1338

@ParthiKarnan  see https://github.com/dotnet/docs/pull/20598 which will be live soon.

@smitpatel can you close this duplicate

**Closed** 2020-09-17 22:13 UTC
Labels: area-tools, type-enhancement

**Comment by Rick-Anderson** [comment] 2020-09-18 00:12
@ParthiKarnan  see https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration
