### ISSUE TITLE
Sample code is wrong

### ISSUE THREAD

**Issue by vhe1** [dotnet/EntityFramework.Docs#2647] opened 2020-09-16 20:38 UTC
Doc is wrong.
Tried to do the first example:
```
    public static class xxx
    {
        static MigrationBuilder CreateUser(
            this MigrationBuilder migrationBuilder,
            string name,
            string password)
            => migrationBuilder.Sql($"CREATE USER {name} WITH PASSWORD '{password}';");

    }
```
Doesn't compile because migrationBuilder.Sql is the wrong type:
`Cannot implicitly convert type 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.OperationBuilder<Microsoft.EntityFrameworkCore.Migrations.Operations.SqlOperation>' to 'Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Custom Migrations Operations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment] 2020-09-22 19:22
Duplicate of #1574

**Closed by bricelam** 2020-09-22 19:22 UTC
Labels: area-migrations
