### ISSUE TITLE
One to many without navigation properties with a collection of IDs in the parent

### ISSUE THREAD

**Issue by sikora507** [dotnet/EntityFramework.Docs#4474] opened 2023-09-01 13:59 UTC
How can I configure something like this?
```csharp
// Principal (parent)
public class Blog
{
    public int Id { get; set; }
    **public ICollection<int> PostIds {get; set;}**
}

// Dependent (child)
public class Post
{
    public int Id { get; set; }
    public int BlogId { get; set; } // Required foreign key property
}
```

I try to follow Domain Driven Design and let's pretend both Blog and Post are my aggregate roots. They cannot reference each other directly (but only by IDs). What I want is to have a collection of **PostIds inside Blog**. I cannot seem to configure that using entity framework as it will require a navigation property to do it. Or can I?

**Comment by ajcvickers** [comment] 2023-09-25 19:39
Duplicate of https://github.com/dotnet/efcore/issues/31683

**Closed** 2023-10-04 15:56 UTC
