### ISSUE TITLE
Needs a proof read.

### ISSUE THREAD

**Issue by M3hl** [dotnet/EntityFramework.Docs#4139] opened 2022-11-15 21:27 UTC
[Enter feedback here]
For example, I can't parse this sentence: "The FK linking the mapped tables is targeting the same properties on which it is declared.".  As someone trying to use this info for reference, the to's from's and other subtleties get lost without punctuation and word choice. If I was confident in the intent, I would suggest replacement text.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c847da37-ca7d-1c42-8acf-405167085d27
* Version Independent ID: bd4fe1c7-514d-cfb1-d975-4096306b06e9
* Content: [Advanced table mapping - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/table-splitting)
* Content Source: [entity-framework/core/modeling/table-splitting.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/table-splitting.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment] 2022-11-16 02:58
Foreign keys are defined between two sets of properties - the ones it's declared on and the ones it's targeting - the principal key. In the case of linking FKs both sets of properties are the same.

**Comment by ajcvickers** [comment] 2022-11-19 10:47
@M3hl We're having difficult seeing multiple interpretations of this. Can you be more specific about what is ambiguous or could be clearer here? Maybe suggest some replacement texts based on what the intent could be?

**Comment by ajcvickers** [comment] 2022-11-30 20:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-11-30 20:44 UTC
