### ISSUE TITLE
The documentation on this page could stand for a little improvement.   Give me a hint what does "defining navigation name" mean.  Looks a little autogenerated.

### ISSUE THREAD

**Issue by inlguy** [dotnet/EntityFramework.Docs#2781] opened 2020-10-15 20:11 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea9a698-0616-d3ee-bd7c-8e901ddbb624
* Version Independent ID: 48aea069-bb4f-f591-cbe5-d85c02a3343f
* Content: [ModelExtensions.FindEntityType Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.modelextensions.findentitytype?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/ModelExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/ModelExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment] 2020-10-19 04:40
We can't explain every term each time is used, instead we'll create a glossary page for reference.

Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/1665

**Closed by AndriySvyryd** 2020-10-19 04:40 UTC
Labels: closed-duplicate
