### ISSUE TITLE
Incorrect example for rowversion

### ISSUE THREAD

**Issue by stuartlynch** [dotnet/EntityFramework.Docs#4754] opened 2024-06-21 06:02 UTC
### Type of issue

Other (describe below)

### Description

```
modelBuilder.Entity<Blog>()
    .Property(e => e.RowVersion)
    .HasConversion<byte[]>()
    .IsRowVersion();
```
In this example I think the ".HasConversion<byte[]>" is not required. This is how it was done in ef core 6 but now the .HasConverion<byte[]> is implied?

### Page URL

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#numeric-rowversions-for-sql-azuresql-server

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md

### Document Version Independent Id

97203c5d-fe52-b71e-dcb3-71c9492b4e04

### Article author

@ajcvickers

**Comment by ajcvickers** [comment] 2024-07-15 17:21
Thanks for reporting. Duplicate of #4725.

**Closed by ajcvickers** 2024-07-15 17:21 UTC
