### ISSUE TITLE
Extension method provided in the docs for projecting coordinates using ProjNet isn't compiling.

### ISSUE THREAD

**Issue by jayasurya-jeyakodi** [dotnet/EntityFramework.Docs#2891] opened 2020-11-21 05:13 UTC
[Enter feedback here]
Extension method provided in the docs for projecting coordinates using ProjNet isn't compiling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dcf82b-f177-e91b-96a5-67f2f57bd6c4
* Version Independent ID: 89c0803f-570f-07a6-6dc2-285678712c86
* Content: [Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/spatial)
* Content Source: [entity-framework/core/modeling/spatial.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-11-24 17:15
@jayasurya-jeyakodi Can you be more specific about what is not working? When I run this code from the downloaded sample, it compiles and prints:

```
/home/ajcvickers/.dotnet/dotnet /home/ajcvickers/dotnet/efdocs/samples/core/Spatial/Projections/bin/Debug/net5.0/Projections.dll
Degrees: 0.2175
Meters:  17,062
```

**Comment by bricelam** [comment] 2020-12-01 00:29
We even have a GitHub action to [build our samples](https://github.com/dotnet/EntityFramework.Docs/actions?query=workflow%3A%22Build+Samples%22) so make sure they compile.

**Comment by ajcvickers** [comment] 2020-12-01 16:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2020-12-01 16:47 UTC
