### ISSUE TITLE
Issue with ToQueryString().

### ISSUE THREAD

**Issue by mshinnie** [dotnet/EntityFramework.Docs#2317] opened 2020-04-23 16:21 UTC
So I am trying the preview version "5.0.0-preview.3.20181.2" both as the globally installed dotnet-ef and the nugget packages I am using.  I am not able to use the ToQueryString() after making a query as the compiler complains the method doesnt exist. 
``` 
            var query = context.CampaignData.Where(a => a.CampaignId>1);
            var sql = query.ToQueryString();
```

Here is my cs proj file nugget packages 
```
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.6"/>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.0-preview2.20084.1"/>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-preview.3.20181.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.3.20181.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-preview.3.20181.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0-preview.3.20181.2"/>
```
Thank you. 

This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by ajcvickers** [comment] 2020-04-24 16:49
@mshinnie Please post your full csproj file so we can take a look.

**Comment by mshinnie** [comment] 2020-04-24 19:13
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.6"/>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.0-preview2.20084.1"/>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-preview.3.20181.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.3.20181.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-preview.3.20181.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0-preview.3.20181.2"/>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetDir)bin\$(ProjectName).dll&quot; &quot;$(TargetDir)$(ProjectName).dll&quot;"/>
  </Target>
</Project>
```

**Comment by ajcvickers** [comment] 2020-04-27 19:39
@mshinnie I am not able to reproduce this. I created a project using your csproj and I am able to use ToQueryString without any issues. Can you attach a full project where you are seeing this issue and I'll see if I can reproduce with that.

**Comment by ajcvickers** [comment] 2020-05-04 16:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-05-04 16:57 UTC
