### ISSUE TITLE
Update page for .NET 6

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/EntityFramework.Docs#3829] opened 2022-04-20 12:09 UTC
Update the page for .NET 6 which uses nullable reference types.

The code:
```cs
public DbSet<Blog> Blogs { get; set; }
public DbSet<Post> Posts { get; set; }
```
Will complain that:

    CS8618	Non-nullable property 'Blogs' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
    CS8618	Non-nullable property 'Posts' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-04-20 13:51
Duplicate of #3575

**Closed** 2022-04-22 19:22 UTC
Labels: closed-duplicate
