### ISSUE TITLE
I just get stuck trying to apply the example to my own setting.

### ISSUE THREAD

**Issue by the-dag** [dotnet/EntityFramework.Docs#4355] opened 2023-05-23 10:49 UTC
I want to test using proper, pure code-first and make use of EF migrations, to see how that experience compares to the "manually modify both the code and database" approach that is the way it's done at my company. I started a new project, but didn't begin at the EF end. I've structured it as a class library that should contain the business logic and data access code, and added a CLI (console) project as well as Blazor Client + Server projects. My DbContext class lives in my Lib (class library) and unlike the provided sample, I haven't hard-coded the connection string to the database instance.

The solution builds without errors, but when I attempt to use the same steps you provided in the "Visual Studio" section, I quickly get stuck. I selected Lib, my class library that contains my DbContext class(es), as the "default project" in Package Manager Console (what EF migrations have to do with package management is beyond me, but that is a separate issue). The `Install-Package` step succeeeds, but `Add-Migration InitialCreate` prints "Build started..." and then "Build failed.", which is only slightly more informative than saying "something went wrong". All the projects build without errors, but what "build" in this context actually means is not for me to know, since in this brave new world nobody is supposed to understand how anything works, just know how to use it... :)

IF build here means something like find DbContext classes in the library and instantiate them, and from that obtain the connection string, and from that do some kind of inspection of a database instance, it might have to do with how I implemented my DbContext. I want to simplify my life by having an intermediate class inheriting from DbContext from which I can derive my other DbContexts. This intermediate class takes care of some boilerplate such as use SQL server, use SplitQuery behaviour, and get your connection string from configuration: 

    public abstract class MyCompanyDbContext : DbContext 
    {
        public MyCompanyDbContext() : base(new DbContextOptions<DbTools>()) {}

        public MyCompanyDbContext(string configuredConnectionStringName): base(new DbContextOptions<DbTools>()) 
        {
            this.connectionStringName = Guard.NotNullOrWhitespace(configuredConnectionStringName, nameof(configuredConnectionStringName));
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            var cnxStr = AppConfig.GetConnectionString(ConnectionStringName);
            optionsBuilder.UseSqlServer(cnxStr, ConfigureSqlServer);
        }

        private readonly string connectionStringName;

        private string ConnectionStringName
            => connectionStringName ?? GetType().Name;

        private void ConfigureSqlServer(SqlServerDbContextOptionsBuilder mssql)
        {
            mssql.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
        }
    }

Then the concrete type (it is extremely simple so far):

    public class ArtemisDb : MyCompanyDbContext
    {
        public DbSet<SomeEntity> Entities { get; set; }
    }    

Where the entity type in turn just has a few primitive props (string Name, DateTime created, that sort of thing).

Now, I do not want this to turn into a discussion about what is the right way to make DbContexts. I have my reasons for wanting to structure things this way. I mention it because it means (a) I've got an abstract class inheriting DbContext, and I've got logic that will throw exceptions if expected config is not present. I don't *think* `Add-Migration` actually needs to execute any of my code (it seems to me it merely needs to do some reflection on the assembly) but since I really know nothing about how this works, I figured it is worth mentioning.

I'm not sure what the best way to rectify the problem is. I didn't try doing the exact example, but nor do I see how it would help me get unstuck if I did and everything worked. Probably you won't know what to do with my feedback either, but on the off chance that this can give you some idea (add a troubleshooting section perhaps, IDK), I figured I'd share.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-05-23 15:10
> All the projects build without errors, but what "build" in this context actually means is not for me to know, since in this brave new world nobody is supposed to understand how anything works, just know how to use it... :)

All that is happening here is a build of the solution. If the solution builds fine in Visual Studio, but you get an error here, then that sounds like a bug. Can you attach your solution so that we can investigate?

**Comment by ajcvickers** [comment] 2023-06-07 19:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-06-07 19:16 UTC
