### ISSUE TITLE
Foreign Key Validation error with nullable check 

### ISSUE THREAD

**Issue by ValeLouvet** [dotnet/EntityFramework.Docs#4449] opened 2023-08-13 07:30 UTC
If you have nullable checked activated, this code does not work.
The work around is to set the Blog property in Post as nullable.
But, it should not be the case for an entity where this foreign key is mandatory.
The validation error is:
"The propery Blog is required."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0fb981-4dec-7ff7-817b-6606f620b875
* Version Independent ID: c7517e7d-f011-a24c-53da-913771913998
* Content: [Saving Related Data - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/related-data)
* Content Source: [entity-framework/core/saving/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-09-20 19:46
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-10-04 15:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-10-04 15:56 UTC

**Comment by ValeLouvet** [comment] 2023-10-04 16:14
public class Post
  {
      public int PostId { get; set; }
      public string Title { get; set; }
      public string Content { get; set; }
      public int BlogId { get; set; }
      public Blog Blog { get; set; }
  }
  
In Net 6, the Blog property is not nullable in case nullable check is activated.
This throws an error if Blog is defined as a foreign key and you try to insert a Post without getting the blog from context.
