### ISSUE TITLE
Missing FileGroup specification

### ISSUE THREAD

**Issue by aspnerd** [dotnet/EntityFramework.Docs#2528] opened 2020-07-21 03:33 UTC
There doesn't appear to be any support for Filegroups. This is something that is available in SQL Server and should be an option to specify for indexes, tables, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1a7f80-8950-41c9-fe60-90899382b5f0
* Version Independent ID: c58f6f6f-bedd-f62c-4f0f-f4f8545c8aa6
* Content: [MigrationBuilder.CreateIndex Method (Microsoft.EntityFrameworkCore.Migrations)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.migrationbuilder.createindex?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Migrations/MigrationBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Migrations/MigrationBuilder.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-07-21 18:33
Duplicate of https://github.com/dotnet/efcore/issues/12272

**Closed by ajcvickers** 2020-07-21 18:33 UTC
