### ISSUE TITLE
documentation on dbfunctions i dont see any page about dbfunctions

### ISSUE THREAD

**Issue by hoksource** [dotnet/EntityFramework.Docs#2538] opened 2020-07-27 17:47 UTC
Good day,

i tried searching for dbfunctions class and extension methods and it is only seen at migration/changelogs. If possible add atleast a page about it for ef core. 

Also i can't find anything about fulltext search

thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview of Entity Framework Core - EF Core](https://docs.microsoft.com/en-us/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment] 2020-07-28 00:40
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/500

**Closed by AndriySvyryd** 2020-07-28 00:40 UTC
