### ISSUE TITLE
No migrations

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/EntityFramework.Docs#3372] opened 2021-08-09 15:03 UTC
For those just starting out coding the examples are great but to a novice my bet is they will get lost without a database so it might be a good idea to include migrations or provide the schema to create the databases used in the GitHub repo code samples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9a8e9e-a397-64b9-419d-fbcf525c3698
* Version Independent ID: f10c27f0-4b5b-c2b7-dd32-fac7b0d8060e
* Content: [Interceptors - EF Core](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#savechanges-interception)
* Content Source: [entity-framework/core/logging-events-diagnostics/interceptors.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/logging-events-diagnostics/interceptors.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-08-10 09:09
@karenpayneoregon The samples as downloaded from GitHub should have everything in them to create the database needed for the sample to run. Did you find a case where you needed to do something additional?

**Comment by ajcvickers** [comment] 2021-08-20 16:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-08-20 16:52 UTC
