### ISSUE TITLE
Table Splitting page is broken

### ISSUE THREAD

**Issue by mrlife** [dotnet/EntityFramework.Docs#2942] opened 2020-12-14 15:21 UTC
Only main content is present, links are broken, etc.

https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

**Comment by ajcvickers** [comment] 2020-12-15 19:56
@mrlife Thanks for reporting this. It has been root caused to an issue in the docs infrastructure which will be addressed by the docs team. Closing the issue here.

**Closed by ajcvickers** 2020-12-15 19:56 UTC
