### ISSUE TITLE
The cyclic dependency part is unclear

### ISSUE THREAD

**Issue by jeancallisti** [dotnet/EntityFramework.Docs#3463] opened 2021-10-04 14:27 UTC
The cyclic dependency part is unclear. What does changing the output directory do? Do I end up with two versions of the migrations project? Do I still need to add a reference to this alternative build of the Migrations project to the other project? Etc.
Please provide a step by step explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment] 2021-10-04 21:10
It's not the only part...

Duplicate of #933

**Closed** 2021-10-06 10:07 UTC
Labels: closed-duplicate
