### ISSUE TITLE
Add example for WPF on .NET Core 3.x

### ISSUE THREAD

**Issue by MacOkieh** [dotnet/EntityFramework.Docs#1957] opened 2019-12-03 15:45 UTC
By default there is no app.config file in a WPF project on .NET Core 3.x . Would be nice to see some sort of "how-to".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-06-06 23:15
Duplicate of #778

**Closed by ajcvickers** 2020-06-06 23:15 UTC
Labels: area-context-management, type-enhancement
