### ISSUE TITLE
Please extend docs with ClientCascade option

### ISSUE THREAD

**Issue by norvegec** [dotnet/EntityFramework.Docs#2499] opened 2020-07-08 13:16 UTC
ClientCascade option is undocumented.
---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-07-09 22:40
Duplicate of #2426

**Closed by ajcvickers** 2020-07-09 22:40 UTC
