### ISSUE TITLE
the project's target framework does not contain entity framework runtime assembles

### ISSUE THREAD

**Issue by rogerio-rgo** [dotnet/EntityFramework.Docs#3789] opened 2022-03-30 04:26 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73b2e5a-9526-e664-a2da-556717d344e1
* Version Independent ID: 93442b78-6869-139c-bdbc-9a1efa21b7a6
* Content: [Databinding with WPF - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf)
* Content Source: [entity-framework/ef6/fundamentals/databinding/wpf.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/databinding/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-04-01 15:54
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-04-19 12:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-04-19 12:57 UTC
