### ISSUE TITLE
Incorrect command line syntax

### ISSUE THREAD

**Issue by LennyThompson** [dotnet/EntityFramework.Docs#4110] opened 2022-11-02 21:06 UTC
The following command is provided for installing custom templates for efcore scaffolding

dotnet new install Microsoft.EntityFrameworkCore.Templates::7.0.0-*

This should be 

dotnet new -i Microsoft.EntityFrameworkCore.Templates::7.0.0-*

or 

dotnet new --install Microsoft.EntityFrameworkCore.Templates::7.0.0-*

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Version Independent ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Content: [Custom Reverse Engineering Templates - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding/templates.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/templates.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment] 2022-11-03 16:38
Duplicate of #4100

**Closed** 2022-11-07 15:59 UTC
Labels: closed-duplicate
