### ISSUE TITLE
Generate sql script for migration in another project during runtime

### ISSUE THREAD

**Issue by svenhue** [dotnet/EntityFramework.Docs#4200] opened 2023-01-07 00:08 UTC
Hi,
im trying to create sql scripts for my migrations during runtime.
I basically want to migrate models during runtime, but i prefer using sql scripts instead of a typical migration.

```
            Assembly a = Assembly.LoadFrom(fullpath); // in this assembly are the entity, dbcontext and an application service
            Type servicetype = a.GetExportedTypes().Where(t => t.FullName.Contains("ObjectService")).First();
            object entityservice = Activator.CreateInstance(servicetype, new object[] { "ConnectionString", null, null });
            PropertyInfo prop = entityservice.GetType().GetProperty("_dbContext");
            DbContext db = (DbContext) prop.GetValue(entityservice);

            var serviceCollection = new ServiceCollection();
            serviceCollection.AddEntityFrameworkDesignTimeServices();
            serviceCollection.AddDbContextDesignTimeServices(db);

            var serviceProvider = serviceCollection.BuildServiceProvider();
            
            var migrator = serviceProvider.GetService<IMigrator>();
            
            migrator.GenerateScript("20230105185813_OrderMigration"); // cant find the migration
            // or
            migrator.Migrate(); //same
```

My problem is that the migrator cant find any migrations. 
The migrations are generated during runtime with the IMigrationsScaffolder service and the related dbcontext sets the migrationassembly to another project. (Startup project is a Http api, the dbmigrator and the application are both class librays)

When i change this code to code below, it works as expected.

```
     DbContextOptionsBuilder<OrderEntityDbContext> options = new DbContextOptionsBuilder<OrderEntityDbContext>();

            options.UseSqlServer("connectionstring", x => x.MigrationsAssembly("DataCenter.DbMigrator"));
          
            OrderEntityDbContext context = new OrderEntityDbContext(options.Options);

            context.Database.Migrate();
```

Here is my code that creates the migration and the model snapshot (which works fine):

```
     var serviceCollection = new ServiceCollection();
            serviceCollection.AddEntityFrameworkDesignTimeServices();
            serviceCollection.AddDbContextDesignTimeServices(db);

            var provider = db.GetService<IDatabaseProvider>().Name;
            var providerAssembly = Assembly.Load(new AssemblyName(provider));
            var providerServicesAttribute = providerAssembly.GetCustomAttribute<DesignTimeProviderServicesAttribute>();
            var designTimeServicesType = providerAssembly.GetType(providerServicesAttribute.TypeName, throwOnError: true);
            ((IDesignTimeServices)Activator.CreateInstance(designTimeServicesType)!).ConfigureDesignTimeServices(serviceCollection);
            var serviceProvider = serviceCollection.BuildServiceProvider();
            // Add a migration
            var migrationsScaffolder = serviceProvider.GetService<IMigrationsScaffolder>();
            var migration = migrationsScaffolder.ScaffoldMigration(migrationName, rootNamespace);
            
            migrationsScaffolder.Save(projectDir, migration, outputDir);

```
So how can i instruct the IMigrator service to get the correct migrations? How does ist locate the migrations?
Note that the application dont know the dbcontext or migrations at startup because i load the assemblys dynamically. 

This is the string that the roslyn compiler will compile to the assembly i am creating the instances of. (I use String.Format() that why there are some {0} )

         public class {0}EntityObjectService 
                    {{
                        public {0}EntityDbContext _dbContext {{ get; set; }}

                        public {0}EntityObjectService(string connectionstring, string? databaseprovider, string? migrationproject)
                        {{
                            DbContextOptionsBuilder<{0}EntityDbContext> options = new DbContextOptionsBuilder<{0}EntityDbContext>();

                            if (databaseprovider == null && migrationproject == null)
                            {{
                                Console.Write(""Choosing db options"");
                                options.UseSqlServer(connectionstring, x => x.MigrationsAssembly(""DataCenter.DbMigrator""));
                            }}
                            else if (databaseprovider == null && migrationproject != null)
                            {{
                                options.UseSqlServer(connectionstring, x => x.MigrationsAssembly(migrationproject));
                            }}
                            else if (databaseprovider == ""npgsql"" && migrationproject == null)
                            {{
                                options.UseNpgsql(connectionstring, x => x.MigrationsAssembly(""DataCenter.DbMigrator""));
                            }}
                            else if (databaseprovider == ""npgsql"" && migrationproject != null)
                            {{
                                options.UseNpgsql(connectionstring, x => x.MigrationsAssembly(migrationproject));
                            }}
                            else if (databaseprovider == ""mongodb"")
                            {{
                                //no solution yet
                            }}

                            _dbContext = new {0}EntityDbContext(options.Options);
                        }}

                        public async Task<List<{0}Entity>> GetAllAsync()
                        {{

                            return await _dbContext.Set<{0}Entity>().ToListAsync();

                        }}

                    }}

**Comment by svenhue** [comment] 2023-01-09 21:38
I changed my code generation strategy to only compile at design time, this solved a lot of problems i had with this approach.

**Comment by svenhue** [comment] 2023-01-11 22:05
Hi,
as i wrote i solved a lot of issues by changing my code generation strategy....
But the original issue is still not solved.

As i mentioned i can migrate my migrations when i use this:

```
     DbContextOptionsBuilder<OrderEntityDbContext> options = new DbContextOptionsBuilder<OrderEntityDbContext>();

            options.UseSqlServer("connectionstring", x => x.MigrationsAssembly("DataCenter.DbMigrator"));
          
            OrderEntityDbContext context = new OrderEntityDbContext(options.Options);

            context.Database.Migrate();
```

But when i use this: (the assembly is shown above) no migrations are found.
```

        string fullpath = String.Format("{0}{1}EntityDb/{1}EntityObjectService.dll", path, o.Name);
            Assembly a = Assembly.LoadFrom(fullpath);
            Type servicetype = a.GetExportedTypes().Where(t => t.FullName.Contains("ObjectService")).First();
            object entityservice = Activator.CreateInstance(servicetype, new object[] { "Server=DESKTOP-2AA0NTD,1433;Database=alpha.datacenter;User ID=alpha;Password=alpha;TrustServerCertificate=True", null, null });
            PropertyInfo prop = entityservice.GetType().GetProperty("_dbContext");
            DbContext db = (DbContext)prop.GetValue(entityservice);
            
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddEntityFrameworkDesignTimeServices();
            serviceCollection.AddDbContextDesignTimeServices(db);
            
            var serviceProvider = serviceCollection.BuildServiceProvider();
            
            var migrator = serviceProvider.GetService<IMigrator>();

            migrator.Migrate();
```

I think that has something to do with AssemblyLoadContext but i cant really figure out  whats the problem.
I also tried to place all files in the same project, but nothing changes

Please help!

**Comment by ajcvickers** [comment] 2023-01-12 18:36
@svenhue This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-01-24 17:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-24 17:46 UTC
Labels: closed-question
