### ISSUE TITLE
The samples are not runnable, come on people

### ISSUE THREAD

**Issue by derekjwilliams** [dotnet/EntityFramework.Docs#3142] opened 2021-03-09 02:18 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33851e00-5992-c9c8-d9b6-428ba8bde6a9
* Version Independent ID: 793410c2-2e9f-e31e-7e2c-ac766eac451b
* Content: [Testing code that uses EF Core - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/)
* Content Source: [entity-framework/core/testing/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/testing/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-03-09 15:18
@derekjwilliams What error are you seeing when you try to run the sample?

**Comment by ajcvickers** [comment] 2021-03-19 16:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-03-19 16:47 UTC
