### ISSUE TITLE
FromSqlRaw() issue while async call

### ISSUE THREAD

**Issue by vijaysahu12** [dotnet/EntityFramework.Docs#2350] opened 2020-05-01 14:35 UTC
Why **_FirstOrDefaultAsync()_** is not working with **_FromSqlRaw()_** method.

### **Not Working Example:** 
```
  var res = await db.SpCustomerRegistration
                        .FromSqlRaw( spProcedureName,
                        obj.FirstName , obj.LastName)
                        .FirstOrDefaultAsync();
```
**For above example getting this exception :**
FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it. Consider calling `AsEnumerable` after the FromSqlRaw or FromSqlInterpolated method to perform the composition on the client side.

### **Working Example:** 
```
  var res = await db.SpCustomerRegistration
                        .FromSqlRaw( spProcedureName,
                        obj.FirstName , obj.LastName) 
                        .AsAsyncEnumerable()
                       .GetAsyncEnumerator()
                       .MoveNextAsync();

```

Even it will work if I use **_ToListAsync_()** and then **_FirstOrDefault_()**
**Here is the example:**
  ```
 var res = await db.SpCustomerRegistration
                        .FromSqlRaw( spProcedureName,
                        obj.FirstName , obj.LastName)
                        .ToListAsync();
return res.FirstOrDefault().ProertyName;

```
**Note**: I have used proper syntax for task and await 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-05-01 15:49
Duplicate of https://github.com/dotnet/efcore/issues/18205

**Closed by ajcvickers** 2020-05-01 15:49 UTC
