### ISSUE TITLE
Migrations in a separate class library project does not work.

### ISSUE THREAD

**Issue by tekbyts** [dotnet/EntityFramework.Docs#3974] opened 2022-08-09 18:05 UTC
The steps mentioned in this https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli are not working. I run into an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-08-09 18:06
@tekbyts you'll have to at least post the error so we know what happened. Please also post the steps you did, one by one.

**Comment by ajcvickers** [comment] 2022-08-24 10:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-24 10:20 UTC
