### ISSUE TITLE
Sample Code is Missing

### ISSUE THREAD

**Issue by erhanalankus** [dotnet/EntityFramework.Docs#3800] opened 2022-04-05 19:19 UTC
See the first code sample, "Simple Logging" tab.

Right after this sentence:
> EF makes it very easy to capture command execution times, via either simple logging or Microsoft.Extensions.Logging:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57b4b8e9-fcec-2f12-0ceb-f4a2405543e2
* Version Independent ID: 7e461d12-0aef-9901-080a-19246ae4fa04
* Content: [Performance Diagnosis - EF Core](https://docs.microsoft.com/en-us/ef/core/performance/performance-diagnosis?tabs=simple-logging%2Cload-entities)
* Content Source: [entity-framework/core/performance/performance-diagnosis.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/performance-diagnosis.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-04-07 09:16
Duplicate of #3779

**Comment by roji** [comment] 2022-04-07 09:16
This has been fixed but not yet pushed to live.

**Closed by roji** 2022-04-07 09:16 UTC
