### ISSUE TITLE
Guidance on how to make sure Microsoft.EntityFrameworkCore.Design isn't removed from the project.

### ISSUE THREAD

**Issue by martingbrown** [dotnet/EntityFramework.Docs#4422] opened 2023-07-21 15:06 UTC
I follow the instructions to the letter, but when I get to running:

`dotnet ef migrations add InitialCreate`

I get the error:

`Your startup project 'MyConsole' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.`

It appears that even though Visual Studio is installing the package and adding it to the project, when the project is built, because it isn't using the package, the compiler is removing it again. If I uninstall the package, reinstall it and add some noddy line of code that actually uses the library it starts working. For example I added this:

`Console.WriteLine(Microsoft.EntityFrameworkCore.Design.EntityFrameworkDesignServicesBuilder.CoreServices.Count);`

Now I have migrations I can remove this line again and all keeps working because the added migration code references the package.

I would appreciate some guidance in the docs about how to tackle this.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations Overview - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment] 2023-07-21 15:38
Can you share more about your solution? Are there multiple projects? Which packages are installed into which projects? Which project are you running the command from?

**Comment by ajcvickers** [comment] 2023-08-02 19:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-08-02 19:27 UTC
