### ISSUE TITLE
Duplicate description for same fields

### ISSUE THREAD

**Issue by jasase** [dotnet/EntityFramework.Docs#3846] opened 2022-05-04 08:51 UTC
Description for fields `NoAction` and `Restrict` is completly the same. Is this intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-05-07 20:15
Duplicate of #2212.

**Closed by ajcvickers** 2022-05-07 20:15 UTC
