### ISSUE TITLE
Migration creates table for Entity<T>.HasNoKey()

### ISSUE THREAD

**Issue by bdaniel7** [dotnet/EntityFramework.Docs#2360] opened 2020-05-04 13:31 UTC
In EF Core 2.2 I had the following:
```
public class NomenclatureVersionDto
{
	public int Id { get; set; }
	public string Nomenclature { get; set; }
	public int Year { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	base.OnModelCreating(modelBuilder);
	modelBuilder.Query<NomenclatureVersionDto>();
}

await dbContext.Query<NomenclatureVersionDto>()
					.FromSqlRaw(query)
					.AsNoTracking()
					.SingleOrDefaultAsync();

```
And it worked.
Now, with EF Core 3.1, I have to declare it
```
modelBuilder.Entity<NomenclatureVersionDto>().HasNoKey();
```

But now when I add a migration, a script to create a table mapped to NomenclatureVersionDto is created.
How do I avoid this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc10f39-8fe5-e856-5839-9aa5e9d435c6
* Version Independent ID: 10ddba97-42d2-0cda-3e7f-eaeb4fda74b0
* Content: [Keyless Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/keyless-entity-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/keyless-entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by smitpatel** [comment] 2020-05-04 15:48
Map keyless entity to a view. You can use `ToView(null)` if there is no corresponding view in the database. This will mark that the entity type is not mapped to a table hence migrations will not create a table.

**Comment by ajcvickers** [comment] 2020-05-04 19:38
Duplicate of #2124

**Closed by ajcvickers** 2020-05-04 19:38 UTC
