### ISSUE TITLE
Very poor documentation! Please explain the sample codes. Please also provide scenarios where it could be used.

### ISSUE THREAD

**Issue by geetmenon** [dotnet/EntityFramework.Docs#4025] opened 2022-09-13 00:34 UTC
For e.g. in the section "Shared-type entity types and property bags", the documentation is so poor that we can't understand anything. I clicked on the property bags link  `https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties#property-bag-entity-types`  hoping it will provide a detailed explanation. But that was even worse.  Remember, the documentation is not for Microsoft but the external users/developers. So give proper explanation (especially of the examples) so that we can actually appreciate the feature and start using it (instead of making it very confusing or ambiguous for the developers). These features are of no use if you have it but we can't use it for lack of proper documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32360b50-1129-b3d2-2d71-c6b89cd9f2c6
* Version Independent ID: 4f18f8dc-5cd5-cb37-0f59-fb1767609b2b
* Content: [What's New in EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-09-17 07:49
Duplicate of #3198

**Closed by ajcvickers** 2022-09-17 07:49 UTC

**Comment by geetmenon** [comment] 2022-09-17 08:26
Please do not close it saying it is a duplicate of some ticket. The documentation on this page in general is very unclear. The Shared-type entity types and property bags was just one example. For e.g. "an entity can be mapped to a SQL query " under Flexible Entity Mapping section --- what exactly does it mean. Just giving an example without explaining what exactly it means and what scenario this feature could be used etc renders it unusable for the readers. Please keep the developers in mind when creating documentation.
