### ISSUE TITLE
Wrong Method under Deleting Data

### ISSUE THREAD

**Issue by arenner-git** [dotnet/EntityFramework.Docs#4408] opened 2023-07-05 08:16 UTC
under "Deleting Data" the wrong Method (.Add) is stated and referenced:

> Use the [DbSet<TEntity>.Add](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.add) method to delete instances

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23f8db8b-8ee6-86c9-7cb2-b5802214ec13
* Version Independent ID: b959839c-684e-5d60-650e-0af17c971c79
* Content: [Basic SaveChanges - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/basic)
* Content Source: [entity-framework/core/saving/basic.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/basic.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2023-07-05 08:43
Duplicate of #4362

**Comment by roji** [comment] 2023-07-05 08:43
This has already been fixed, but we haven't yet pushed the docs live (/cc @ajcvickers)

**Closed** 2023-07-07 18:45 UTC
Labels: closed-duplicate
