### ISSUE TITLE
piggyback split queries

### ISSUE THREAD

**Issue by DickBaker** [dotnet/EntityFramework.Docs#4045] opened 2022-09-20 18:15 UTC
Docpage states "Each query currently implies an additional network roundtrip to your database." but surely this ain't necessarily so ? I supposethat current EF would batch the 1st & 2nd (i.e. split) query into a single TSQL request payload, so achieves a single round-trip [i.e. not needing MARS to multiplex the session, and EF also receives & digests both resultsets from a single tx from MSSQL/etc]
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://learn.microsoft.com/en-gb/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-09-20 18:17
Duplicate of https://github.com/dotnet/efcore/issues/10878

**Comment by roji** [comment] 2022-09-20 18:18
Note that you still need MARS if you don't want to buffer the first resultset - that's orthogonal to batching.

**Comment by DickBaker** [comment] 2022-09-20 18:33
agreed "In some scenarios", but my beef was the docs emphatically state "implies an additional network roundtrip" which I think is outdated by your modern EF smarts. Again, leave in your capable hands to do/not & close. Thanks.

**Comment by DickBaker** [comment] 2022-09-20 18:43
Earlier I had raised another Issue about split queries, but can't find the Issue in my "Participating" filter [can't see how to show Closed, so maybe I never pushed the Submit button]. Anyway I am re-submitting Issue against that page, so please don't be cross if it dupes!

**Comment by DickBaker** [comment] 2022-09-20 18:57
please ignore the "Earlier I had .." comment as #4044 eventually surfaced (so I erased the #4046 dup)

**Comment by roji** [comment] 2022-09-20 19:09
No problem (and definitely not cross). 

> but my beef was the docs emphatically state "implies an additional network roundtrip" which I think is outdated by your modern EF smarts

What makes you think this? As far as I'm aware, split queries *always* send the 2nd query as a separate roundtrip (assuming the 2nd query is sent at all).

**Comment by DickBaker** [comment] 2022-09-20 19:22
I thought I had read/seen one of the EF team introduce the batching of those 2 partial queries into a single trip, but I can't pinpoint it [maybe I just dreamed it?!] or it was a 3rd-party extension. Never mind, I bow to your superior knowledge and I certainly haven't profiled it to justify my claim. I simply thought the docs were outdated and were not crediting more recent EF smarts. But what do I know?!

**Comment by roji** [comment] 2022-09-20 19:24
@DickBaker it's pretty to test this out: you can just turn on logging and see whether there are two database commands or just one. It's a great way to play around with EF and see exactly what SQL it's generating and how it's executing it (e.g. when batching is in use).

Anyway, I'll go ahead and close this as a duplicate of https://github.com/dotnet/efcore/issues/10878.

**Closed by roji** 2022-09-20 19:24 UTC
