### ISSUE TITLE
Incorrect nested list data update in cosmos db container EF 6.1

### ISSUE THREAD

**Issue by MS13Arya** [dotnet/EntityFramework.Docs#4375] opened 2023-06-09 04:35 UTC
Hi,

Facing a issue with entity framework while updating the nested list records with UOM.

Database: Cosmos DB
using **Collection** type data as a list to update the item. I am trying to remove the first record from the nested collection but values are replaced by by first index to second index item. & First index item removed.

Issue: **Second index item replaced by first index item.**

Please provide the solution or fixed version

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by ajcvickers** [comment] 2023-06-13 12:31
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-06-13 16:11
@MS13Arya There isn't enough here to be able to reproduce what you are seeing. We code that we can actually run so that we can investigate why it is behaving in the way it does.

**Comment by ajcvickers** [comment] 2023-07-12 19:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-07-12 19:11 UTC
