### ISSUE TITLE
Multiple includes with odd behavior populating navigating properties

### ISSUE THREAD

**Issue by tgsfranchi** [dotnet/EntityFramework.Docs#4112] opened 2022-11-04 17:56 UTC
I'm facing an odd behavior with multiple includes when selecting without use AsNoTracking().

I basically have something like this:

var x = context.PA.Include(a => a.TO).Include(a => a.FC).Include(a => a.Pr).ToList();
var y = context.PA.Include(a => a.TO).Include(a => a.FC).Include(a => a.Pr).AsNoTracking().ToList();

Per what I saw on logging, both have resulted on the same DB query, however for x list not all navigation properties have been loaded successfully (PA, TO and FC gets loaded like at random, eventually none are loaded, eventually all are loaded, I could not stablish any pattern), while on y, every navigation property got populated properly.

I have:

    public class PA
    {
        public TO TO { get; set; }
        public int IdTO { get; set; }
        public Pr Pr { get; set; }
        public int IdPr { get; set; }
        public FC FC { get; set; }
        public int IdFC { get; set; }
        public decimal VM { get; set; }
        public string HL { get; set; }
        public string NU{ get; set; }
    }
    public class TO
    {
        public int Id { get; set; }
        public string N { get; set; }
        public decimal? PS { get; set; }
        public string NU { get; set; }
        public PA PA { get; set; }
    }
    public class Pr
    {
        public int ID { get; set; }
        public string D { get; set; }
        public int QD { get; set; }
        public string NU { get; set; }
        public PA PA { get; set; }
    }
    public class FC
    {
        public int Id { get; set; }
        public string D { get; set; }
        public decimal PC { get; set; }
        public string NU { get; set; }
        public PA PA { get; set; }
    }

My ModelCreating Mapping:

                modelBuilder.Entity<Pr>(buildAction =>
                {
                    buildAction.ToTable("TB_PR");
                    buildAction.Property<int>(x => x.ID).IsRequired().HasColumnName("ID_PR").HasColumnType("NUMBER(6)").UseHiLo("SEQ_PR");
                    buildAction.Property<string>(x => x.D).IsRequired().HasColumnName("DS_PR").HasColumnType("VARCHAR2(20)");
                    buildAction.Property<int>(x => x.QD).IsRequired().HasColumnName("QD_PR").HasColumnType("NUMBER(6)");
                    buildAction.Property<string?>(x => x.NU).HasColumnName("NU_PR").HasColumnType("VARCHAR2(30)");
                    buildAction.HasKey(x => x.ID);
                    buildAction.HasIndex(x => x.QD).IsUnique();
                    buildAction.HasIndex(x => x.D).IsUnique();
                });
                modelBuilder.Entity<FC>(buildAction =>
                {
                    buildAction.ToTable("TBS_FC");
                    buildAction.Property<int>(x => x.Id).IsRequired().HasColumnName("ID_FC").HasColumnType("NUMBER(6)").UseHiLo("SEQ_FC");
                    buildAction.Property<string>(x => x.D).IsRequired().HasColumnName("DS_FC").HasColumnType("VARCHAR2(20)");
                    buildAction.Property<decimal>(x => x.PC).IsRequired().HasColumnName("PC_FC").HasColumnType("NUMBER(5,2)");
                    buildAction.Property<string?>(x => x.NU).HasColumnName("NU_FC").HasColumnType("VARCHAR2(30)");
                    buildAction.HasKey(x => x.Id);
                    buildAction.HasIndex(x => x.D).IsUnique();
                    buildAction.HasIndex(x => x.PC).IsUnique();
                });
                modelBuilder.Entity<TO>(buildAction =>
                {
                    buildAction.ToTable("TBS_TO");
                    buildAction.Property<int>(x => x.Id).IsRequired().HasColumnName("ID_TO").HasColumnType("NUMBER(6)").UseHiLo("SEQ_TO");
                    buildAction.Property<string>(x => x.N).IsRequired().HasColumnName("NM_TO").HasColumnType("VARCHAR2(30)");
                    buildAction.Property<decimal?>(x => x.PS).HasColumnName("PS_TO").HasColumnType("NUMBER(5,2)");
                    buildAction.Property<string>(x => x.NU).HasColumnName("NU_TO").HasColumnType("VARCHAR2(30)");
                    buildAction.HasKey(x => x.Id);
                    buildAction.HasIndex(x => x.N).IsUnique();
                });
                modelBuilder.Entity<PA>(buildAction =>
                {
                    buildAction.ToTable("TBS_PA");
                    buildAction.Property<int>(x => x.IdTO).IsRequired().HasColumnName("ID_TO").HasColumnType("NUMBER(6)");
                    buildAction.Property<int>(x => x.IdPr).IsRequired().HasColumnName("ID_PR").HasColumnType("NUMBER(6)");
                    buildAction.Property<int>(x => x.IdFC).IsRequired().HasColumnName("ID_FC").HasColumnType("NUMBER(6)");
                    buildAction.Property<decimal>(x => x.VM).IsRequired().HasColumnName("VM_PA").HasColumnType("NUMBER(15,2)");
                    buildAction.Property<string>(x => x.HL).IsRequired().HasColumnName("HL_PA").HasColumnType("VARCHAR2(8)");
                    buildAction.Property<string>(x => x.NU).IsRequired().HasColumnName("NU_PA").HasColumnType("VARCHAR2(30)");
                    buildAction.HasKey(x => new { x.IdTO, x.IdPr, x.IdFC });
                    buildAction.HasOne(x => x.TO).WithOne(x => x.PA).HasForeignKey<PA>(x => x.IdTO);
                    buildAction.HasOne(x => x.Pr).WithOne(x => x.PA).HasForeignKey<PA>(x => x.IdPr);
                    buildAction.HasOne(x => x.FC).WithOne(x => x.PA).HasForeignKey<PA>(x => x.IdFC);
                    buildAction.Navigation(x => x.TO).UsePropertyAccessMode(PropertyAccessMode.Property);
                    buildAction.Navigation(x => x.FC).UsePropertyAccessMode(PropertyAccessMode.Property);
                    buildAction.Navigation(x => x.Pr).UsePropertyAccessMode(PropertyAccessMode.Property);
                });

I'm using Oracle.EntityFrameworkCore 6.21.5
Microsoft.EntityFrameworkCore 6.0
Connecting to a Oracle11g database

Am I missing something?
Luckly, for this time I have no need of using AsNoTracking, so I'm safe, however I'm very curious about why do I get this very odd behavior not using the AsNoTracking and getting my navigation oroperly populated at random...

![xAll](https://user-images.githubusercontent.com/106002012/200043649-918addd0-ea2f-4d63-9b67-91c7a907aa95.png)
![yFcTo](https://user-images.githubusercontent.com/106002012/200043651-41e02a37-36d2-4bb3-adc3-a31097596ea5.png)
![Ynone](https://user-images.githubusercontent.com/106002012/200043654-ca8a1d51-d724-44d5-813e-d40a2217b220.png)
![Yfc](https://user-images.githubusercontent.com/106002012/200043657-ba414a9e-8f88-4f12-b4d5-06170d69c87f.png)
random...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-11-07 16:01
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-11-16 20:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-16 20:12 UTC
