### ISSUE TITLE
Same description

### ISSUE THREAD

**Issue by McMaartenz** [dotnet/EntityFramework.Docs#4340] opened 2023-05-09 07:43 UTC
[Enter feedback here]
Why is it saying the same description for 
ClientSetNull
NoAction
Restrict
SetNull

---
#### Document Details

⚠ *Do not eedit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-05-10 08:26
Duplicate of https://github.com/dotnet/efcore/issues/29261.

**Closed by ajcvickers** 2023-05-10 08:26 UTC
