### ISSUE TITLE
Should also talk about how to use annotations to define indexes

### ISSUE THREAD

**Issue by david30xie** [dotnet/EntityFramework.Docs#2940] opened 2020-12-12 21:42 UTC
As title implies, we should also talk about how to use annotations to define indexes. I checked [Indexes](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations#index) from EF 6, but it doesn't work for EF Core. The error I got is below:

![image](https://user-images.githubusercontent.com/100747/101995572-cb79a100-3cc2-11eb-9a43-5b0355aaddcf.png)

It says Index is only valid for 'Class', which is not right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Indexes - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/indexes)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2020-12-13 06:57
Duplicate of #2937

**Closed** 2020-12-15 17:28 UTC
Labels: closed-duplicate
