### ISSUE TITLE
StringComparison options in .NET 6

### ISSUE THREAD

**Issue by frank-hoffman** [dotnet/EntityFramework.Docs#3839] opened 2022-04-26 15:59 UTC
I think this documentation may be a bit out of date, at least for .NET 6. When I use StringComparison.CurrentCultureIgnoreCase, I can see the engine translate the query using ToLower. No exception is thrown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27be469-3758-941c-0c5d-3a54b1545493
* Version Independent ID: d89924aa-668e-229c-8170-5731c3fff4c1
* Content: [Collations and case sensitivity - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity)
* Content Source: [entity-framework/core/miscellaneous/collations-and-case-sensitivity.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/collations-and-case-sensitivity.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by frank-hoffman** [comment] 2022-04-26 16:28
SQL Server

**Comment by roji** [comment] 2022-04-26 16:39
Using string.Equals with StringComparison.CurrentCultureIgnoreCase on SQL Server throws a translation failure exception for me (see code below). Can you please double-check your code, and if you're convinced your code is correct, post a minimal, runnable code sample (simple to my code below)?

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = ctx.Blogs.Where(b => b.Name.Equals("foo", StringComparison.CurrentCultureIgnoreCase)).ToList();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>

**Comment by ajcvickers** [comment] 2022-05-06 16:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-05-06 16:43 UTC
