### ISSUE TITLE
Example assumes I don't want to overwrite the primary key - what if the operation is perfectly fine?

### ISSUE THREAD

**Issue by Snappee** [dotnet/EntityFramework.Docs#3963] opened 2022-07-31 17:02 UTC
The example shows only ONE valid way to deal with the concurrency issue - with the assumption that the exception caught the issue and the original values should be re-read from the database as such and maybe the user needs to be informed.   

What it doesn't talk about, nor show is what if the issue is NOT an issue - that the desired functionality was to CHANGE a key field?   I can manually use the SQL Manager to change a key field - as there are no conflicts with other tables (dependencies) - but EF Core will throw a concurrency exception as if there is.

What I don't know is WHAT needs to be done to complete the primary key edit?   Is this an issue due to having the same records displayed in a DataGrid view?  (And now I'm trying to pragmatically edit a primary key field and save the changes?).

You need to enhance the example and not assume that the concurrency always catches a conflict - as there may not really be one.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Snappee** [comment] 2022-08-01 12:26
Hey Arthur . . . will put together a little Winforms C# example later this
week - though it will have a small database (SQL Server backup) with it (as
my guess is that it will need the DB and the DataGridView that binds to it).

All the Best,

Dale O. Hays
SINNOVATE
East Bay Labs
VHP - Vintage Horsepower
cell:     614-404-8641
eMails:  ***@***.***, ***@***.***,
***@***.***,



Quote of the Month:  "*Positive Dissatisfaction is a key driver of many new
products . . . it can ALWAYS be better!**" -* Dale Hays

**Comment by ajcvickers** [comment] 2022-08-15 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-15 16:37 UTC
