### ISSUE TITLE
Migration Scripts Missing?

### ISSUE THREAD

**Issue by keithnicholson** [dotnet/EntityFramework.Docs#2168] opened 2020-03-06 21:38 UTC
This issue tracker is for ***documentation***

Good day!  I am attempting to work with the Samples provided for the documentation.  I cloned the entire solution.  It seems that the necessary database objects are not able to be created in the projects.  The EFGetStarted project has the Migrations folder, excluding DataSeeding, the others do not.  So when I try to execute the Querying project, there is a lot missing.  

I started in the Program.cs file and made a call to RawSQL.Sample.Run().  yet dbo.Blogs does not exist since the database does not.  The BloggingContext.cs page references the db, EFQuerying.

Have I overlooked something?

Peace,
Keith Nicholson

**Comment by ajcvickers** [comment] 2020-03-09 15:32
@keithnicholson Thanks for reporting this. We have some work to do to make our samples easier to use--see #1817. 

For now, you should be able to set a connection string to a temp database and then use:

```
context.Database.EnsureDeleted();
context.Database.EnsureCreated();
```

This will give you a clean database each time you run the sample. Make sure not to use a connection string to a database you don't want to delete!

**Comment by ajcvickers** [comment] 2020-03-09 22:45
Closing as duplicate of #1817

**Closed** 2020-03-13 16:58 UTC
Labels: closed-duplicate
