### ISSUE TITLE
Add a dedicated documentation page for `ExecuteUpdate` and `ExecuteDelete`

### ISSUE THREAD

**Issue by xamir82** [dotnet/EntityFramework.Docs#4333] opened 2023-04-28 17:16 UTC
`ExecuteUpdate` and `ExecuteDelete` were introduced in EF7 but they still don't have their own documentation. The only place they're mentioned is in the [What's new in EF Core 7.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates) post.

Why?! This is an outrageously useful and important feature and yet it's not yet well-known, and the main reason for that is likely the lack of documentation.

**Comment by roji** [comment] 2023-04-29 15:45
Duplicate of #4032

**Closed by roji** 2023-04-29 15:45 UTC
