### ISSUE TITLE
Additional useful info

### ISSUE THREAD

**Issue by chriswhitts** [dotnet/EntityFramework.Docs#2510] opened 2020-07-11 21:15 UTC
For the Asp.Net core section it would be useful to mention the following as it is not always included by default in Asp.Net core templates as witnessed by a few StackOverflow questions. Adding the using statement for `Microsoft.Extensions.Configuration` does not fix compile time errors on it's own:

_Do not forget to add via DI:_

`public IConfiguration Configuration { get; }`
`public Startup(IConfiguration configuration)
{
    Configuration = configuration;
}`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-gb/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-07-13 16:44
@chriswhitts Can you point to the templates involved?

**Comment by ajcvickers** [comment] 2020-07-24 16:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-07-24 16:12 UTC
