### ISSUE TITLE
Repository provided in the examples has complex entity setups and relationships, but doesn't use them in a real-world manner

### ISSUE THREAD

**Issue by IanKemp** [dotnet/EntityFramework.Docs#3564] opened 2021-11-16 11:47 UTC
Take this example:

```
var query = from photo in context.Set<PersonPhoto>()
            join person in context.Set<Person>()
                on photo.PersonPhotoId equals person.PhotoId
            select new { person, photo };
```

You now have an anonymous object containing pair of entities that are completely unrelated, whereas a more real-world example would returns a single `Person` with its child `Photos` collection populated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1acf84-126c-f01d-b39a-ab077819351f
* Version Independent ID: 5d3bdd6d-ad0e-e306-5aef-0d5adea892b6
* Content: [Complex Query Operators - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators)
* Content Source: [entity-framework/core/querying/complex-query-operators.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/complex-query-operators.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-11-16 20:53
@IanKemp The point of the example is to show that a Person with a populated Photos collection is not needed. That being said, can you write a more compelling example? We can potentially include it as well.

**Comment by ajcvickers** [comment] 2021-11-30 11:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-11-30 11:13 UTC
