### ISSUE TITLE
Clarify how to add children to a database

### ISSUE THREAD

**Issue by mc0re** [dotnet/EntityFramework.Docs#2330] opened 2020-04-28 05:46 UTC
Consider Entity &lt;-&gt; Model mapping. What is the best approach to create / update child entries with regards to their navigational / foreign key properties? I mean, mapping "Child entity includes parent entity" -&gt; "Child model with parent object reference" -&gt; "New child entity object with new parent object" does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-04-28 14:51
> New child entity object with new parent object" does not work.

Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing that doesn't work so that we can investigate.

**Comment by ajcvickers** [comment] 2020-05-08 15:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-05-08 15:28 UTC
