### ISSUE TITLE
Where is `EntityTypeConfiguration.t4`

### ISSUE THREAD

**Issue by luetm** [dotnet/EntityFramework.Docs#4103] opened 2022-10-27 10:46 UTC
Where can this this third party template `EntityTypeConfiguration.t4` be found? I can't find anything with google... I mean Bing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Version Independent ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Content: [Custom Reverse Engineering Templates - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding/templates.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/templates.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-10-27 10:47
Duplicate of #4088

**Closed by ajcvickers** 2022-10-27 10:47 UTC
