### ISSUE TITLE
What's the difference between various DeleteBehaviors?

### ISSUE THREAD

**Issue by ivanyurchenko1** [dotnet/EntityFramework.Docs#3336] opened 2021-07-19 00:42 UTC
It's not clear what is the difference between the DeleteBehaviors is. The documentation sections for DeleteBehavior.SetNull, DeleteBehavior.Restrict and DeleteBehavior.NoAction are completely the same. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-07-19 08:50
Duplicate of #2212

**Comment by roji** [comment] 2021-07-19 08:51
As @AndriySvyryd wrote in #2212:

> They are essentially the same. Restrict throws immediately, while NoAction throws when the transaction is commited.

**Closed** 2021-07-20 16:21 UTC
Labels: closed-duplicate
