### ISSUE TITLE
DeleteBehavior Enum Documentation Appears To Be Incorrect

### ISSUE THREAD

**Issue by conradakunga** [dotnet/EntityFramework.Docs#4465] opened 2023-08-28 18:16 UTC
This documentation is unclear.

![image](https://github.com/dotnet/EntityFramework.Docs/assets/1281845/fc37df89-68cc-4651-8899-1308591755ca)

1. `Cascade `and `ClientCascade` have the exact same definitions.
1. `ClientSetNull` `NoAction` `Restrict` and `SetNull` all have the exact same definition, going all the way back to EF Core 2.2. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-09-20 19:47
Duplicate of https://github.com/dotnet/efcore/issues/29261

**Closed by ajcvickers** 2023-09-20 19:47 UTC
