### ISSUE TITLE
need clarification

### ISSUE THREAD

**Issue by ish-1313** [dotnet/EntityFramework.Docs#3736] opened 2022-02-17 15:44 UTC
[Enter feedback here]
When EF Core creates instances of these types, such as for the results of a query, it will first call the default parameterless constructor and then set each property to the value from the database. However, **if EF Core finds** a parameterized constructor with parameter names and types that match those of mapped properties, then **it will instead** call the parameterized constructor with values for those properties and will not set each property explicitly. For example:

in reality, if entity has parameterless constructor then ef core will not call parameterized constructor. at least 6.0.2 version
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc7aedf-6301-7ec7-4f65-81749b1f54c8
* Version Independent ID: d0774ffa-c841-e6df-72de-d7f53c0d6f6f
* Content: [Entity types with constructors - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/constructors)
* Content Source: [entity-framework/core/modeling/constructors.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/constructors.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-02-18 13:16
Duplicate of #2571. See also https://github.com/dotnet/efcore/issues/27466

**Closed by ajcvickers** 2022-02-18 13:16 UTC
