### ISSUE TITLE
How to handle left outer joins with EF 3.1.10 . We are getting errors on version upgrade

### ISSUE THREAD

**Issue by amit21thakur** [dotnet/EntityFramework.Docs#2874] opened 2020-11-16 06:29 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1acf84-126c-f01d-b39a-ab077819351f
* Version Independent ID: 5d3bdd6d-ad0e-e306-5aef-0d5adea892b6
* Content: [Complex Query Operators - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators)
* Content Source: [entity-framework/core/querying/complex-query-operators.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/complex-query-operators.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-11-16 16:45
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-11-23 17:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-11-23 17:10 UTC
