### ISSUE TITLE
It's been 5 years

### ISSUE THREAD

**Issue by kcabral817** [dotnet/EntityFramework.Docs#3265] opened 2021-05-26 15:43 UTC
It's been 5 years since this page was last updated.  Has there been no more advancements during this time to help us migrate a database first EF 6.4 to EF core 5?  This is really scary that nothing seems to be done to help use better migrate.  How about something like a analysis tool to run against our models indicating the unsupported features or issues?  Is the position still that we not migrate from Entity Framework 6 to EF core 5?  I have a need to for some of the new functionality like "Time" and restrictive includes and the performance improvements.  But I'm still seeing big caution signs when reading dated material.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 422e4c63-a5c0-76ef-b30d-5e6ed7a32fe6
* Version Independent ID: 56cadf01-60b9-a9e4-919c-efbb894cabdb
* Content: [Porting from EF6 to EF Core - Porting an EDMX-Based Model - EF](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-edmx)
* Content Source: [entity-framework/efcore-and-ef6/porting/port-edmx.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/efcore-and-ef6/porting/port-edmx.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-06-01 09:18
Duplicate of #1180

**Comment by roji** [comment] 2021-06-01 09:26
@kcabral817 ideally, we'd indeed have better migration documentation. #1180 tracks doing this, and also contains and links to some resources which should be helpful. The reason this hasn't happened to this point is lack of team resources and time towards this, because of other, more highly-prioritized work.

>  How about something like a analysis tool to run against our models indicating the unsupported features or issues?

This is unlikely to happen, since the effort needed in creating such a static analysis tool is huge (think about identifying queries which would need changing), and we generally prefer to invest resources in new features and bug fixes. This has come up in the past, and we generally believe that a good test suite is the ideal way to flush out unsupported features when migrating from EF6 and EF Core (and continues to be useful later as regression tests).

> Is the position still that we not migrate from Entity Framework 6 to EF core 5?

Not at all - the lack of a better EF6->EF Code migration guide doesn't in any way imply that people shouldn't migrate. Anyone needing new features or performance improvements - like you've indicated above - should definitely consider migrating to EF Core, since EF6 will no longer receive new features etc.

**Closed** 2021-06-01 15:56 UTC
Labels: closed-duplicate
