### ISSUE TITLE
Need help to convert to EFcore

### ISSUE THREAD

**Issue by Chittaranjandell** [dotnet/EntityFramework.Docs#3085] opened 2021-02-05 07:38 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1226698-6874-6f8f-f716-1974152243fa
* Version Independent ID: 9e7bdb7a-d3dc-03a2-99f6-78aa46cc8357
* Content: [Porting from EF6 to EF Core - Porting a Code-Based Model - EF](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code#feedback)
* Content Source: [entity-framework/efcore-and-ef6/porting/port-code.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/porting/port-code.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment] 2021-02-05 20:36
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/1180

**Closed by AndriySvyryd** 2021-02-05 20:36 UTC
