### ISSUE TITLE
Update fwlinks

### ISSUE THREAD

**Issue by smitpatel** [dotnet/EntityFramework.Docs#2634] opened 2020-09-11 20:22 UTC
https://go.microsoft.com/fwlink/?linkid=2131316 -> https://docs.microsoft.com/en-us/ef/core/querying/filters#accessing-entity-with-query-filter-using-required-navigation

https://go.microsoft.com/fwlink/?linkid=2134277 once the split pages go to live

**Comment by smitpatel** [comment] 2020-09-11 22:38
https://go.microsoft.com/fwlink/?linkid=2129535 points to base docs and used in exception message that string.Equals cannot be used with string comparison.

**Comment by JeremyLikness** [comment] 2020-09-18 21:10
2131316 is updated. What's the status on 2134277 ... what should it point to? Where should I redirect 2129535? /cc @smitpatel @ajcvickers

**Comment by smitpatel** [comment] 2020-09-18 21:15
2134277, you already updated the other day from PR.
2129535 should probably file a new issue and point to it till we have some docs for it? @dotnet/efteam

**Comment by JeremyLikness** [comment] 2020-10-19 22:06
Pinging on this ... any action here @smitpatel @ajcvickers ? Not clear on what specific doc we are waiting to go live for this.

**Comment by smitpatel** [comment] 2020-10-19 22:59
https://github.com/dotnet/EntityFramework.Docs/issues/2634#issuecomment-691341532 is still pending.

**Comment by ajcvickers** [comment] 2020-10-20 17:19
@JeremyLikness I'm not aware of anything else.

**Comment by ajcvickers** [comment] 2020-12-16 20:35
Closing as dupe of #409

**Closed by ajcvickers** 2020-12-16 20:35 UTC
Labels: area-global, type-cleanup
