### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by mcurko** [dotnet/EntityFramework.Docs#2316] opened 2020-04-23 11:41 UTC
From Microsoft:
https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key
=&gt;
"When there are multiple navigation properties defined between two types (that is, more than just one pair of navigations that point to each other) the relationships represented by the navigation properties are ambiguous. You will need to manually configure them to resolve the ambiguity."

This was not the case in EF 2.0, but I'm unable to find this breaking change on the list!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#feedback)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-04-24 16:13
@mcumming If this isn't https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#mersa, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-05-04 16:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-05-04 16:57 UTC
