### ISSUE TITLE
Scaffold-DbContext or Migration commands : most parameters don't work : ContextNamespace etc. 

### ISSUE THREAD

**Issue by Nk54** [dotnet/EntityFramework.Docs#2420] opened 2020-06-03 12:26 UTC
kind of error I got :
Scaffold-DbContext : A parameter cannot be found that matches parameter name 'ContextNamespace'.

Same happens for most of parameters available in package manager console.

I've followed the documentation and installed latest nuget packages.

The basic parameters works but not the optional ones.

**Comment by roji** [comment] 2020-06-03 14:06
@Nk54 can you post the full command which you are trying and which fails?

**Comment by ajcvickers** [comment] 2020-06-12 16:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-06-12 16:38 UTC
