### ISSUE TITLE
Document DeleteBehavior.ClientNoAction 

### ISSUE THREAD

**Issue by UliPlabst** [dotnet/EntityFramework.Docs#4238] opened 2023-02-02 09:00 UTC
I build and Application that uses Soft-Delete patterns. As others, I have implemented Soft-Delete by overriding SaveChangesAsync() on DbContext. I find deleted EntityEntries and set the Deleted timestamp and set the EntityState to Modified. Unfortunately when the EntityState was set to Deleted earlier, all Links from related Objects to the Entity will get set to null.  
I think the Soft-Delte use case where we do not want to sever links to soft-deleted objects is a very common and valid one. Configuring the link with DeleteBehavior.NoAction did not solve the issue, as contrary to it's name DeleteBehavior.NoAction is actually the same as DeleteBehavior.SetNull (according to the documentation [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-7.0)).  
To configure the DeleteBehavior to actually do nothing, the problem was solved with DeleteBehavior.ClientNoAction. This actually solved my problem, but what it does is not documented and the name is misleading. 

At least update the documentation of DeleteBehavior.ClientNoAction to reflect what it actually does, as it solved my problem but I do not know which other side effects it might have.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2023-02-03 19:44
Duplicate of https://github.com/dotnet/efcore/issues/29261

**Closed** 2023-02-08 20:01 UTC
