### ISSUE TITLE
EFCore Nullable Owned entity type Obsolete documentation

### ISSUE THREAD

**Issue by Davilink** [dotnet/EntityFramework.Docs#2591] opened 2020-08-25 17:52 UTC
In the documentation : https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#current-shortcomings

![image](https://user-images.githubusercontent.com/1498932/91211710-389a0400-e6dd-11ea-8561-b8f1749baa0e.png)

Since EFCore 3.0, it is possible.
https://github.com/dotnet/EntityFramework.Docs/issues/1646

Also, you should put an example with the nullable constraints activated (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types). A good example/caveat is when you have an entity that all his property are null, the value return by EFCore is a null value, not an empty object so the type of the property (that use an owned entity type) should be nullable, but when all or one of the property are required then the type of the property should not be nullable.

**Comment by AndriySvyryd** [comment] 2020-08-26 02:16
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2320

**Closed by AndriySvyryd** 2020-08-26 02:16 UTC

**Comment by Davilink** [comment] 2020-08-26 13:59
@AndriySvyryd 
Should i open a new issue or post in the referenced issue for this part
> Also, you should put an example with the nullable constraints activated (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types). A good example/caveat is when you have an entity that all his property are null, the value return by EFCore is a null value, not an empty object so the type of the property (that use an owned entity type) should be nullable, but when all or one of the property are required then the type of the property should not be nullable.

**Comment by AndriySvyryd** [comment] 2020-08-26 17:16
@Davilink You can comment on #2320
