### ISSUE TITLE
Which Exception is thrown?

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [dotnet/EntityFramework.Docs#2165] opened 2020-03-05 12:11 UTC
These methods "throw an exception if there is not exactly one element in the sequence." It would be great if it was documented *which* exception was thrown so that I could catch it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b7deb0-a592-b6dc-1564-fba73a4dcb4c
* Version Independent ID: 1836b7d9-419e-d8a4-51ff-09f504a56462
* Content: [EntityFrameworkQueryableExtensions.SingleAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.singleasync?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-03-05 16:34
Duplicate of https://github.com/dotnet/efcore/issues/20086

**Closed by ajcvickers** 2020-03-05 16:34 UTC
