### ISSUE TITLE
Unable to complete EF Core Tools with UWP tutorial

### ISSUE THREAD

**Issue by aybe** [dotnet/EntityFramework.Docs#2692] opened 2020-09-25 19:15 UTC
Following the exact instructions in it, it doesn't want to work at this step:

PM> Add-Migration InitialCreate
Startup project 'abcd' is a Universal Windows Platform app. This version of the Entity Framework Core Package Manager Console Tools doesn't support this type of project. For more information on using the EF Core Tools with UWP projects, see https://go.microsoft.com/fwlink/?linkid=858496

Note: the link in the error message points to the same page.

(Visual Studio 2019 Version 16.7.4)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-09-28 22:48
Duplicate of #2672.

**Closed by ajcvickers** 2020-09-28 22:48 UTC
