### ISSUE TITLE
How do you show underlying SQL query in EF Core?

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/EntityFramework.Docs#3208] opened 2021-04-16 20:14 UTC
See [this SO thread](https://stackoverflow.com/questions/45893732/how-do-you-show-underlying-sql-query-in-ef-core) with 47K views. [Several other SO threads](https://www.google.com/search?q=entity+framework+core+show+sql+in+output+window&rlz=1C1CHBF_enUS801US801&oq=entity+framework+core+show+SQL+output&aqs=chrome.1.69i57j0i22i30.11816j0j7&sourceid=chrome&ie=UTF-8)  on the same question. I was unable to find an official doc on this. See [my Answer](https://stackoverflow.com/a/66662556/502537)

Where is the right place to document this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a1cdc0-8bda-0188-1231-35c1656ff6d1
* Version Independent ID: 79cfe1f9-1139-c191-8a4b-1697a9f23f23
* Content: [Overview of logging and interception - EF Core](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/)
* Content Source: [entity-framework/core/logging-events-diagnostics/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/logging-events-diagnostics/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-04-17 16:31
Duplicate of #1331

**Comment by roji** [comment] 2021-04-17 16:32
If you set up simple logging as described [in the docs](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging) (by just adding `LogTo(Console.WriteLine)`), you'll get the SQL logged out, among other things. Otherwise you can use ToQueryString in the debugger (or in code) on a query to see what SQL it would send.

**Comment by roji** [comment] 2021-04-17 16:33
Oops, thought this came from a user :)

Yeah, it does seem like we're lacking some details on "how to see SQL" front and center, which is probably what 90% of users are looking for in logging.

**Closed** 2021-04-19 15:27 UTC
