### ISSUE TITLE
Could you please add an example specific to seeding pattern?

### ISSUE THREAD

**Issue by blueelvis** [dotnet/EntityFramework.Docs#2117] opened 2020-02-15 21:38 UTC
Hi,

Could you please add some more documentation on how to ensure initial data is seeded in Cosmos with an example specific to it?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by ajcvickers** [comment] 2020-02-19 17:10
@blueelvis What specifically is different about Cosmos from the other providers when it comes to seeding?

**Comment by ajcvickers** [comment] 2020-02-28 17:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-02-28 17:38 UTC
