### ISSUE TITLE
"The value of shadow key property is unknown" when updating document having a collection of owned types without defined key

### ISSUE THREAD

**Issue by emulic** [dotnet/EntityFramework.Docs#3930] opened 2022-07-13 14:17 UTC
[Enter feedback here]
The document is saying "The owned entities don't need to provide explicit key values to be stored"
The provided example for adding a new document is properly working:
```
var distributor = new Distributor
{
    Id = 1,
    ShippingCenters = new HashSet<StreetAddress>
    {
        new StreetAddress { City = "Phoenix", Street = "500 S 48th Street" },
        new StreetAddress { City = "Anaheim", Street = "5650 Dolly Ave" }
    }
};

using (var context = new OrderContext())
{
    context.Add(distributor);

    await context.SaveChangesAsync();
}
```

But trying to update an existing Distributor document will fail with the following exception:
```
The value of shadow key property 'StreetAddress.Id' is unknown when attempting to save changes. 
This is because shadow property values cannot be preserved when the entity is not being tracked. 
Consider adding the property to the entity's .NET type. 
See https://aka.ms/efcore-docs-owned-collections for more information.'
```
This error can be solved by defining a key for the StreetAddress entity. 
I suppose the sentence "The owned entities don't need to provide explicit key values to be stored" is not correct. At least when trying to update an existing document. 

Additionally, it would be great if you could extend the document with an example for updating existing document having a collection of owned types.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-07-23 10:21
@emulic It's not completely clear what you mean by, "when trying to update an existing document." Could you attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate?

**Comment by ajcvickers** [comment] 2022-08-08 15:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-08 15:39 UTC
