### ISSUE TITLE
Related Data and Serialization is out of date

### ISSUE THREAD

**Issue by scottstephens** [dotnet/EntityFramework.Docs#3450] opened 2021-09-30 17:50 UTC
Article describes how to configure json.NET if you are using Asp.net Core. However Asp.net Core no longer uses json.NET for serialization. You should point readers to the Microsoft.AspNetCore.Mvc.JsonOptions.JsonSerializationOptions.ReferenceHandler property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c97686-0345-0dfc-d408-4b7bb94432ac
* Version Independent ID: fd6e0c89-a7a8-bc4a-bc54-449fba2c2ae1
* Content: [Related Data and Serialization - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/serialization)
* Content Source: [entity-framework/core/querying/related-data/serialization.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/serialization.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-10-01 18:34
Duplicate of #2233

**Closed by ajcvickers** 2021-10-01 18:34 UTC
