### ISSUE TITLE
Page Migrations Overview seems incomplete

### ISSUE THREAD

**Issue by luciofassio** [dotnet/EntityFramework.Docs#3077] opened 2020-12-02 08:00 UTC
This page seems missing a part in the end.

In "Create your first migration" section if you click "Visual studio" tab the text that appears is incomplete.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Panoramica delle migrazioni - EF Core](https://docs.microsoft.com/it-it/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs.it-it/blob/live/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-02-04 10:27
@lucianodelucchi under "Creare il database e lo schema", when I click the Visual Studio tab, I can see "Update-Database", which is the right content. Are you seeing something else?

**Comment by ajcvickers** [comment] 2021-02-12 17:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2021-02-12 17:28 UTC
