### ISSUE TITLE
EntityTypeBuilder .HasMany: describe exceptions

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/EntityFramework.Docs#3615] opened 2021-12-11 14:54 UTC
Please explain that [HasMany](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1.hasmany) will throw an [InvalidOperationException](https://docs.microsoft.com/en-us/dotnet/api/system.invalidoperationexception) when the referenced entity is [keyless](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.keylessattribute).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7854295c-db9c-8277-2000-65cffb174234
* Version Independent ID: ddd74ee2-3694-343b-eae2-4cd4a26977a1
* Content: [EntityTypeBuilder&lt;TEntity&gt;.HasMany Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1.hasmany?view=efcore-5.0#Microsoft_EntityFrameworkCore_Metadata_Builders_EntityTypeBuilder_1_HasMany__1_System_Linq_Expressions_Expression_System_Func__0_System_Collections_Generic_IEnumerable___0____)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder`1.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder`1.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2021-12-11 19:54
Duplicate of https://github.com/dotnet/efcore/issues/20086#issuecomment-592704875

**Comment by yecril71pl** [comment] 2021-12-11 20:19
It is not a duplicate. 
* That one: describe exceptions that may be caught.
* This one: describe what not to do or you will get a run time exception.

These use cases are fundamentally different.  Note that it would be much better to catch such errors during build.

**Comment by ajcvickers** [comment] 2021-12-15 16:23
Discussed again in triage. Closing as by-design.

**Closed by ajcvickers** 2021-12-15 16:23 UTC
