### ISSUE TITLE
Document new EF Core 5.0 query translations

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#2079] opened 2020-01-30 22:56 UTC
- [x] DateTime
  - [x] https://github.com/dotnet/efcore/issues/15283
  - [x] https://github.com/dotnet/efcore/issues/17170
  - [x] https://github.com/dotnet/efcore/issues/19273
- [x] Byte arrays
  - [x]  dotnet/efcore#13487
  - [x]  dotnet/efcore#4601
- [x] Reverse
  - [x] https://github.com/dotnet/efcore/issues/17388
- [x] Bitwise operators
  - [x] https://github.com/dotnet/efcore/issues/18788
- [x] Cosmos
  - [x] https://github.com/dotnet/efcore/issues/19800

**Comment by ajcvickers** [comment] 2020-02-03 21:35
Related to #900, but leaving this issue open to collect 5.0 changes.

**Comment by NetMage** [comment] 2020-05-13 20:31
I don't think dotnet/efcore#19273 is done or has anything to do with `DateTime`?

**Comment by bricelam** [comment] 2020-10-12 19:09
Did some of this in PRs #2744, #2746 & #2733

**Comment by smitpatel** [comment] 2020-11-09 23:36
19273 seems wrong reference. (closed as a dupe of open issue)
For Queryable.Reverse - We don't explicitly document queryable methods unless complex ones. (We could call it out in what's new but there is nothing specific in query since support varies widely across providers).
For Bitwise operators - Same as above. We mention function mappings we have added for each providers. Operators mapping is kind of implicity.

I propose close this as fixed.

**Closed** 2020-11-10 16:52 UTC
Labels: area-query, undocumented-feature
