### ISSUE TITLE
Is the documentation unclear on how to use the new IndexAttribute?

### ISSUE THREAD

**Issue by megakevin** [dotnet/EntityFramework.Docs#3273] opened 2021-06-01 00:39 UTC
It looks like, in order to be able to use the `IndexAttribute` as described here: https://docs.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations...

```
[Index(nameof(Name), IsUnique = true)]
```

...one needs to be `using` the `Microsoft.EntityFrameworkCore` namespace.

```
using Microsoft.EntityFrameworkCore;
```

Problem is, nowhere in the docs does it say that the attribute lives in that namespace. Would it be useful to specify that in this doc page?

As an old school .NET developer trying to dive back in with .NET Core, I found it unexpected for this Data Annotation to not be in the `System.ComponentModel.DataAnnotations` or `System.ComponentModel.DataAnnotations.Schema` namespaces. Also, since this attribute is a new feature added in EF Core 5.0, there are still many articles out there claiming that EF Core does not support indexes via Data Annotations, only via Fluent API. Which adds to the confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Indexes - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by terrajobst** [comment] 2021-06-01 02:31
The docs should probably just link to the [API documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.indexattribute?view=efcore-5.0)

**Comment by AndriySvyryd** [comment] 2021-06-04 18:59
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/3281

**Closed by AndriySvyryd** 2021-06-04 18:59 UTC
