### ISSUE TITLE
Please add sample for seeding User & Roles

### ISSUE THREAD

**Issue by papyr** [dotnet/EntityFramework.Docs#4012] opened 2022-09-04 22:08 UTC
Please update the page so that we can easily understand the right way to Seeding users, claims and roles, due to millions ways to do this, has become quite an issue, especially when we override user/role class or add properties to the user class.

Would be nice to have a default /standard way to do this - where the data is checked before seeding in a debug environment only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3437af67-630b-d28f-7fbd-3eedf647f22a
* Version Independent ID: 6c44f987-19a7-c256-e8fa-10378e61cf6e
* Content: [Creating and configuring a model - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/)
* Content Source: [entity-framework/core/modeling/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment] 2022-09-08 00:55
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/736#issuecomment-396322026

**Closed by AndriySvyryd** 2022-09-08 00:55 UTC
Labels: closed-duplicate, area-seeding
