### ISSUE TITLE
System.ArgumentException Missing

### ISSUE THREAD

**Issue by Fjsmoreira** [dotnet/EntityFramework.Docs#2127] opened 2020-02-20 10:06 UTC
If possible please add this exception to your documentation.
Thank you! :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aece550f-d934-0dae-c3ac-0d9b3660bd1a
* Version Independent ID: aebedd48-a65c-c92e-ab4f-f7b4fe467e03
* Content: [DbContext.SaveChangesAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-02-20 20:54
@Fjsmoreira Which specific ArgumentException are you referring to?

**Comment by Fjsmoreira** [comment] 2020-02-21 22:11
While doing the following:
` DbContext.Entry(entity).State = EntityState.Modified;
   await DbContext.SaveChangesAsync();`

If the entity is not modified it will return an ArgumentException.

Or better than updating the documentation, Shouldn't it throw a DBUpdateException ?

**Comment by ajcvickers** [comment] 2020-02-24 16:20
@Fjsmoreira This seems like a bug. Please attach a small, runnable project or post a complete, runnable code listing that reproduces the behavior you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-03-02 17:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-03-02 17:40 UTC
