### ISSUE TITLE
In-Memory Unit Tests

### ISSUE THREAD

**Issue by kmarler18** [dotnet/EntityFramework.Docs#4446] opened 2023-08-11 16:55 UTC
Hi!

I'm attempting to do in-memory testing. I'm following [this article](https://learn.microsoft.com/en-us/ef/core/testing/testing-without-the-database#in-memory-provider). 

The article provides [this template](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Testing/TestingWithoutTheDatabase/InMemoryBloggingControllerTest.cs) for setting up an in-memory test. 

My problem is occurring with the following section of the code in the template.

`BloggingContext CreateContext() => new BloggingContext(_contextOptions, (context, modelBuilder) =>
    {
        #region ToInMemoryQuery
        modelBuilder.Entity<UrlResource>()
            .ToInMemoryQuery(() => context.Blogs.Select(b => new UrlResource { Url = b.Url }));
        #endregion
    });`

When I customize the template to include my DbContext rather than the example BloggingContext I receive the following compiler error. 

"[Your context] does not contain a constructor that takes 2 arguments". 

My question isn't about what the error message means, I know that. My question is, is there a way to achieve what this code is trying to achieve that matches the constructor of my context? 

My DbContext has a parameterless constructor and a constructor that looks like this:

`public [MyContext](DbContextOptions<[MyContext]> options) : base(options)`

Any help is appreciated.

**Comment by ajcvickers** [comment] 2023-09-05 15:17
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-09-20 19:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-09-20 19:45 UTC
