### ISSUE TITLE
 [DatabaseGenerated(DatabaseGeneratedOption.Identity)] and   [DatabaseGenerated(DatabaseGeneratedOption.Computed)] does not perform consistent

### ISSUE THREAD

**Issue by BaldyFreak** [dotnet/EntityFramework.Docs#3794] opened 2022-04-02 06:45 UTC
in entity class when write data an dataAnnotations like this,the entity framework core will generate a default value:
```
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
 public DateTime CreateTime { get; set; } = DateTime.Now;
```
but if i write this,the sqlserver will thow excetion :can not insert null value,column CreateTime

```
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
 public DateTime CreateTime { get; set; } = DateTime.Now;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2022-04-04 11:20
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-04-19 12:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-04-19 12:57 UTC
