### ISSUE TITLE
Replicating xunit test example

### ISSUE THREAD

**Issue by devLarka** [dotnet/EntityFramework.Docs#2381] opened 2020-05-12 20:05 UTC
I trying to replicate your test example and I am getting the following error
The following constructor parameters did not have matching fixture data: DbContextOptions`1 contextOptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5589fb47-8773-6ed5-e152-136bfee49da3
* Version Independent ID: c9f5b694-d1a0-479e-43f2-5dc1fe74590b
* Content: [EF Core testing sample - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/testing-sample#feedback)
* Content Source: [entity-framework/core/miscellaneous/testing/testing-sample.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/testing-sample.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-05-15 16:56
@devLarka Can you compare your code to the downloaded complete sample to see what you might be doing differently?

**Comment by ajcvickers** [comment] 2020-05-22 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-05-22 16:37 UTC
Labels: closed-cannot-reproduce
