### ISSUE TITLE
Add EF Core 6 to the chart on Supported .NET implementations page

### ISSUE THREAD

**Issue by julielerman** [dotnet/EntityFramework.Docs#3596] opened 2021-12-06 19:55 UTC
Add EF Core 6 to the chart on Supported .NET implementations page for clarification and comparison

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720e16e-991f-6802-033c-63269ad8a435
* Version Independent ID: 9d6e9856-615b-0eb0-bf04-6a7ee3d6949d
* Content: [Supported .NET implementations - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms)
* Content Source: [entity-framework/core/miscellaneous/platforms.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/platforms.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-12-06 20:24
Duplicate of #3546

**Closed** 2021-12-13 11:03 UTC
Labels: closed-duplicate
