### ISSUE TITLE
How to use a custom function in the extended function "Select" of IQueryable

### ISSUE THREAD

**Issue by iran1024** [dotnet/EntityFramework.Docs#4003] opened 2022-08-29 06:54 UTC
How to use a custom function in the extended function "Select" of IQueryable
![image](https://user-images.githubusercontent.com/49387318/187140975-0821bd21-b804-47d7-8e35-eef5c947c457.png)

**Comment by ajcvickers** [comment] 2022-08-30 14:36
Duplicate of https://github.com/dotnet/efcore/issues/28914

**Closed by ajcvickers** 2022-08-30 14:36 UTC
