### ISSUE TITLE
Table Per Concrete - Inheritance

### ISSUE THREAD

**Issue by skywalkerisnull** [dotnet/EntityFramework.Docs#3853] opened 2022-05-09 05:56 UTC
This document describes how to do a Table Per Concrete: https://docs.microsoft.com/en-gb/ef/ef6/modeling/code-first/fluent/types-and-properties#mapping-the-table-per-concrete-class-tpc-inheritance

But this page is missing the details on how to implement, or the considerations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance?msclkid=55361e7dcf5c11ec8e3d3abfe1527708)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2022-05-09 08:24
Duplicate of #3764

**Comment by roji** [comment] 2022-05-09 08:24
@skywalkerisnull note that your link above points to the EF6 page - we won't be updating that, only the EF Core docs.

**Closed by roji** 2022-05-09 08:24 UTC
