### ISSUE TITLE
Recommend adding documentation for EF 5 LogTo implementation

### ISSUE THREAD

**Issue by jwooley** [dotnet/EntityFramework.Docs#2729] opened 2020-10-05 03:24 UTC
Logging methods in EF Core 5 can also be done with the new LogTo method on the Context's OptionsBuilder. Add documentation for that new method. See https://erikej.github.io/efcore/2020/05/18/ef-core-simple-logging.html for example.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83069f-39a8-e992-95f7-a8b41154b6f4
* Version Independent ID: 144fe168-080f-6557-e4b2-a18adb4b89ed
* Content: [Logging - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3)
* Content Source: [entity-framework/core/miscellaneous/logging.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/logging.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-10-05 14:55
Duplicate of #2085

**Closed by ajcvickers** 2020-10-05 14:55 UTC
