### ISSUE TITLE
Code sample missing

### ISSUE THREAD

**Issue by SetTrend** [dotnet/EntityFramework.Docs#3072] opened 2021-02-03 22:51 UTC
Some of the code samples in EF Core documentation are missing:

![screenshot](https://user-images.githubusercontent.com/9283914/106819748-83e81380-667a-11eb-9ac7-3945f359dc25.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27be469-3758-941c-0c5d-3a54b1545493
* Version Independent ID: d89924aa-668e-229c-8170-5731c3fff4c1
* Content: [Collations and case sensitivity - EF Core](https://docs.microsoft.com/ef/core/miscellaneous/collations-and-case-sensitivity#database-collation)
* Content Source: [entity-framework/core/miscellaneous/collations-and-case-sensitivity.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/collations-and-case-sensitivity.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2021-02-04 10:49
Duplicate of #3049

**Comment by roji** [comment] 2021-02-04 10:49
This was already in fixed in #3050 but not yet pushed live.

**Closed by roji** 2021-02-04 10:50 UTC

**Comment by SetTrend** [comment] 2021-02-04 11:18
Thank you 👍
